# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-09 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_community_mgmt', '0002_remove_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name2',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
