# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-09 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_community_mgmt', '0003_person_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name2',
        ),
    ]
