# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-09 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_community_mgmt', '0004_remove_person_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='foo', max_length=200),
            preserve_default=False,
        ),
    ]
