FROM python:3.11

WORKDIR /app

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN pip install pytest

ENV PYTHONPATH "${PYTHONPATH}:/"

CMD ["fastapi", "run", "api/main.py", "--port", "80", "--workers", "4"]