# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0057_auto_20210104_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOLRQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs_core.BaseResource', unique=True)),
            ],
        ),
    ]
