from django.conf.urls import url
from hs_core import views
from hs_core.views.autocomplete import autocomplete

urlpatterns = [
    # internal API
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/add-files-to-resource/$',
        views.add_files_to_resource, name='add_files_to_resource'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/change-quota-holder/$',
        views.change_quota_holder, name='change_quota_holder'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/(?P<element_name>[A-z]+)/add-metadata/$',
        views.add_metadata_element, name='add_metadata_element'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/(?P<element_name>[A-z]+)/(?P<element_id>[A-z0-9]+)/update-metadata/$',
        views.update_metadata_element, name='update_metadata_element'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/(?P<element_name>[A-z]+)/(?P<element_id>[A-z0-9]+)/delete-metadata/$',
        views.delete_metadata_element, name='delete_metadata_element'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/update-key-value-metadata/$',
        views.update_key_value_metadata, name="update_key_value_metadata"),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/delete-resource-file/(?P<f>[0-9]+)/$',
        views.delete_file, name='delete_file'),
    url(r'^_internal/(?P<shortkey>[A-z0-9]+)/delete-multiple-files/$',
        views.delete_multiple_files, name='delete_multiple_files'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/delete-resource/$',
        views.delete_resource, name='delete_resource'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/create-new-version-resource/$',
        views.create_new_version_resource, name='create_resource_version'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/copy-resource/$', views.copy_resource,
        name='copy_resource'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/rep-res-bag-to-irods-user-zone/$',
        views.rep_res_bag_to_irods_user_zone, name='replicate_bag_user_zone'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/set-resource-flag/$',
        views.set_resource_flag, name='set_resource_flag'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/share-resource-with-user/(?P<privilege>[a-z]+)/(?P<user_id>[0-9]+)/$',
        views.share_resource_with_user, name='share_resource_with_user'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/unshare-resource-with-user/(?P<user_id>[0-9]+)/$',
        views.unshare_resource_with_user, name='unshare_resource_with_user'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/undo-share-resource-with-user/(?P<user_id>[0-9]+)/$',
        views.undo_share_resource_with_user, name='undo_share_resource_with_user'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/share-resource-with-group/(?P<privilege>[a-z]+)/(?P<group_id>[0-9]+)/$',
        views.share_resource_with_group, name='share_resource_with_group'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/unshare-resource-with-group/(?P<group_id>[0-9]+)/$',
        views.unshare_resource_with_group, name='unshare_resource_with_group'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/undo-share-resource-with-group/(?P<group_id>[0-9]+)/$',
        views.undo_share_resource_with_group, name='undo_share_resource_with_group'),
    url(r'^_internal/create-user-group/$', views.create_user_group, name='create_user_group'),
    url(r'^_internal/update-user-group/(?P<group_id>[0-9]+)$', views.update_user_group,
        name='update_user_group'),
    url(r'^_internal/delete-user-group/(?P<group_id>[0-9]+)$', views.delete_user_group,
        name='delete_user_group'),
    url(r'^_internal/restore-user-group/(?P<group_id>[0-9]+)$', views.restore_user_group,
        name='restore_user_group'),
    url(r'^_internal/share-group-with-user/(?P<group_id>[0-9]+)/(?P<user_id>[0-9]+)/(?P<privilege>[a-z]+)/$',
        views.share_group_with_user, name='share_group_with_user'),
    url(r'^_internal/unshare-group-with-user/(?P<group_id>[0-9]+)/(?P<user_id>[0-9]+)/$',
        views.unshare_group_with_user, name='unshare_group_with_user'),
    url(r'^_internal/make-group-membership-request/(?P<group_id>[0-9]+)/(?P<user_id>[0-9]+)/$',
        views.make_group_membership_request, name='make_group_membership_request'),
    url(r'^_internal/make-group-membership-request/(?P<group_id>[0-9]+)/$',
        views.make_group_membership_request, name='make_group_membership_request'),
    url(r'^_internal/act-on-group-membership-request/(?P<membership_request_id>[0-9]+)/(?P<action>[a-z]+)/$',
        views.act_on_group_membership_request, name='act_on_group_membership_request'),
    url(r'^_internal/group_membership/(?P<token>[-\w]+)/(?P<uidb36>[-\w]+)/(?P<membership_request_id>[0-9]+)/',
        views.group_membership,
        name='group_membership'),
    url(r'^_internal/get-user-or-group-data/(?P<user_or_group_id>[0-9]+)/(?P<is_group>[a-z]+)$',
        views.get_user_or_group_data, name='get_user_or_group_data'),
    url(r'^_internal/(?P<shortkey>[0-9a-f-]+)/publish/$', views.publish),
    url(r'^_internal/create-resource/$', views.create_resource_select_resource_type),
    url(r'^_internal/create-resource/do/$', views.create_resource, name='create_resource'),
    url(r'^_internal/verify-account/$', views.verify_account),
    url(r'^_internal/resend_verification_email/$', views.resend_verification_email),
    url(r'^_internal/(?P<resource_type>[A-z]+)/supported-file-types/$',
        views.get_supported_file_types_for_resource_type, name='resource_type_file_types'),
    url(r'^_internal/(?P<resource_type>[A-z]+)/allow-multiple-file/$',
        views.is_multiple_file_upload_allowed, name="resource_type_multiple_file_upload"),
    url(r'^_internal/search/autocomplete/', autocomplete),
    url(r'^_internal/data-store-structure/$', views.resource_folder_hierarchy.data_store_structure),
    url(r'^_internal/data-store-folder-zip/$',
        views.resource_folder_hierarchy.data_store_folder_zip),
    url(r'^_internal/data-store-folder-unzip/$',
        views.resource_folder_hierarchy.data_store_folder_unzip),
    url(r'^_internal/data-store-create-folder/$',
        views.resource_folder_hierarchy.data_store_create_folder),
    url(r'^_internal/data-store-move-or-rename/$',
        views.resource_folder_hierarchy.data_store_file_or_folder_move_or_rename),
    url(r'^_internal/data-store-move-to-folder/$',
        views.resource_folder_hierarchy.data_store_move_to_folder),
    url(r'^_internal/data-store-rename-file-or-folder/$',
        views.resource_folder_hierarchy.data_store_rename_file_or_folder),
    url(r'^_internal/data-store-delete-folder/$',
        views.resource_folder_hierarchy.data_store_remove_folder),
]
