from django.urls import path, re_path

from hs_core import views
from hs_core.views.autocomplete import autocomplete

urlpatterns = [
    # internal API
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/add-files-to-resource/$",
        views.add_files_to_resource,
        name="add_files_to_resource",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/change-quota-holder/$",
        views.change_quota_holder,
        name="change_quota_holder",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/(?P<element_name>[A-z]+)/add-metadata/$",
        views.add_metadata_element,
        name="add_metadata_element",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/(?P<element_name>[A-z]+)/(?P<element_id>[A-z0-9]+)/update-metadata/$",
        views.update_metadata_element,
        name="update_metadata_element",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/(?P<element_name>[A-z]+)/(?P<element_id>[A-z0-9]+)/delete-metadata/$",
        views.delete_metadata_element,
        name="delete_metadata_element",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/delete-author/(?P<element_id>[A-z0-9]+)/$",
        views.delete_author,
        name="delete_author",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/get-metadata/$",
        views.get_resource_metadata,
        name="get_metadata",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/update-key-value-metadata/$",
        views.update_key_value_metadata,
        name="update_key_value_metadata",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/relevant-tools/$",
        views.get_relevant_tools,
        name="get_relevant_tools",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/delete-resource-file/(?P<f>[0-9]+)/$",
        views.delete_file,
        name="delete_file",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[A-z0-9]+)/delete-multiple-files/$",
        views.delete_multiple_files,
        name="delete_multiple_files",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/delete-resource/(?P<usertext>[A-z]+)/$",
        views.delete_resource,
        name="delete_resource",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/create-new-version-resource/$",
        views.create_new_version_resource,
        name="create_resource_version",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/copy-resource/$",
        views.copy_resource,
        name="copy_resource",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/list-referenced-content/$",
        views.list_referenced_content,
        name="list_referenced_content",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/set-resource-flag/$",
        views.set_resource_flag,
        name="set_resource_flag",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/share-resource-with-user/(?P<privilege>[a-z]+)/(?P<user_id>[0-9]+)/$",
        views.share_resource_with_user,
        name="share_resource_with_user",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/unshare-resource-with-user/(?P<user_id>[0-9]+)/$",
        views.unshare_resource_with_user,
        name="unshare_resource_with_user",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/undo-share-resource-with-user/(?P<user_id>[0-9]+)/$",
        views.undo_share_resource_with_user,
        name="undo_share_resource_with_user",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/share-resource-with-group/(?P<privilege>[a-z]+)/(?P<group_id>[0-9]+)/$",
        views.share_resource_with_group,
        name="share_resource_with_group",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/unshare-resource-with-group/(?P<group_id>[0-9]+)/$",
        views.unshare_resource_with_group,
        name="unshare_resource_with_group",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/undo-share-resource-with-group/(?P<group_id>[0-9]+)/$",
        views.undo_share_resource_with_group,
        name="undo_share_resource_with_group",
    ),
    path(
        "_internal/create-user-group/",
        views.create_user_group,
        name="create_user_group",
    ),
    path(
        "_internal/request-new-community/",
        views.request_new_community,
        name="request_new_community",
    ),
    path(
        "_internal/update-user-community/<int:community_id>",
        views.update_user_community,
        name="update_user_community",
    ),
    path(
        "_internal/update-user-group/<int:group_id>",
        views.update_user_group,
        name="update_user_group",
    ),
    path(
        "_internal/delete-user-group/<int:group_id>",
        views.delete_user_group,
        name="delete_user_group",
    ),
    path(
        "_internal/restore-user-group/<int:group_id>",
        views.restore_user_group,
        name="restore_user_group",
    ),
    re_path(
        r"^_internal/share-group-with-user/(?P<group_id>[0-9]+)/(?P<user_id>[0-9]+)/(?P<privilege>[a-z]+)/$",
        views.share_group_with_user,
        name="share_group_with_user",
    ),
    path(
        "_internal/unshare-group-with-user/<int:group_id>/<int:user_id>/",
        views.unshare_group_with_user,
        name="unshare_group_with_user",
    ),
    path(
        "_internal/make-group-membership-request/<int:group_id>/<int:user_id>/",
        views.make_group_membership_request,
        name="make_group_membership_request",
    ),
    path(
        "_internal/make-group-membership-request/<int:group_id>/",
        views.make_group_membership_request,
        name="make_group_membership_request",
    ),
    re_path(
        r"^_internal/act-on-group-membership-request/(?P<membership_request_id>[0-9]+)/(?P<action>[a-z]+)/$",
        views.act_on_group_membership_request,
        name="act_on_group_membership_request",
    ),
    re_path(
        r"^_internal/group_membership/(?P<token>[-\w]+)/(?P<uidb36>[-\w]+)/(?P<membership_request_id>[0-9]+)/",
        views.group_membership,
        name="group_membership",
    ),
    re_path(
        r"^_internal/metadata_review/(?P<shortkey>[0-9a-f-]+)/"
        r"(?P<action>[a-z]+)/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[-\w]+)/",
        views.metadata_review,
        name="metadata_review"
    ),
    re_path(
        r"^_internal/metadata_review/(?P<shortkey>[0-9a-f-]+)/(?P<action>[a-z]+)/",
        views.metadata_review,
        name="metadata_review_noauth",
    ),
    re_path(
        r"^_internal/spam_allowlist/(?P<shortkey>[0-9a-f-]+)/(?P<action>[a-z]+)/",
        views.spam_allowlist,
        name="spam_allowlist",
    ),
    re_path(
        r"^_internal/get-user-or-group-data/(?P<user_or_group_id>[0-9]+)/(?P<is_group>[a-z]+)$",
        views.get_user_or_group_data,
        name="get_user_or_group_data",
    ),
    re_path(r"^_internal/(?P<shortkey>[0-9a-f-]+)/publish/$", views.publish),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/submit-for-review/$",
        views.submit_for_review,
    ),
    path(
        "_internal/create-resource/do/", views.create_resource, name="create_resource"
    ),
    path("_internal/verify-account/", views.verify_account),
    path("_internal/resend_verification_email/", views.resend_verification_email),
    re_path(
        r"^_internal/(?P<resource_type>[A-z]+)/supported-file-types/$",
        views.get_supported_file_types_for_resource_type,
        name="resource_type_file_types",
    ),
    re_path(
        r"^_internal/(?P<resource_type>[A-z]+)/allow-multiple-file/$",
        views.is_multiple_file_upload_allowed,
        name="resource_type_multiple_file_upload",
    ),
    re_path(r"^_internal/search/autocomplete/", autocomplete),
    path(
        "_internal/data-store-structure/",
        views.resource_folder_hierarchy.data_store_structure,
    ),
    path(
        "_internal/data-store-folder-zip/",
        views.resource_folder_hierarchy.data_store_folder_zip,
        name="zip_folder",
    ),
    path(
        "_internal/zip-by-aggregation-file/",
        views.resource_folder_hierarchy.zip_aggregation_file,
        name="zip_by_aggr_file",
    ),
    path(
        "_internal/data-store-folder-unzip/",
        views.resource_folder_hierarchy.data_store_folder_unzip,
    ),
    path(
        "_internal/data-store-create-folder/",
        views.resource_folder_hierarchy.data_store_create_folder,
    ),
    path(
        "_internal/data-store-add-reference/",
        views.resource_folder_hierarchy.data_store_add_reference,
    ),
    path(
        "_internal/data-store-edit-reference-url/",
        views.resource_folder_hierarchy.data_store_edit_reference_url,
    ),
    path(
        "_internal/data-store-move-or-rename/",
        views.resource_folder_hierarchy.data_store_file_or_folder_move_or_rename,
    ),
    path(
        "_internal/data-store-move-to-folder/",
        views.resource_folder_hierarchy.data_store_move_to_folder,
    ),
    path(
        "_internal/data-store-rename-file-or-folder/",
        views.resource_folder_hierarchy.data_store_rename_file_or_folder,
    ),
    path(
        "_internal/data-store-delete-folder/",
        views.resource_folder_hierarchy.data_store_remove_folder,
    ),
    re_path(
        r"^_internal/update_quota_usage/(?P<username>[\w.@+-]+)/$",
        views.update_quota_usage,
        name="update_quota_usage",
    ),
    re_path(
        r"^_internal/(?P<shortkey>[0-9a-f-]+)/non-preferred-paths/$",
        views.get_non_preferred_paths,
        name="get_non_preferred_paths",
    ),
    path(
        "_internal/get_tasks_by_user/",
        views.get_tasks_by_user,
        name="get_tasks_by_user",
    ),
    re_path(
        r"^_internal/get_task/(?P<task_id>[0-9a-f-]+)$", views.get_task, name="get_task"
    ),
    re_path(
        r"^_internal/abort_task/(?P<task_id>[0-9a-f-]+)$",
        views.abort_task,
        name="abort_task",
    ),
    re_path(
        r"^_internal/dismiss_task/(?P<task_id>[0-9a-f-]+)$",
        views.dismiss_task,
        name="dismiss_task",
    ),
    re_path(
        r"^_internal/set_task_delivered/(?P<task_id>[0-9a-f-]+)$",
        views.set_task_delivered,
        name="set_task_delivered",
    ),
]
