#!/bin/bash

mkdir /tmp/media
rsync -avh --rsh="ssh -p 1338" root@localhost:/home/docker/hydroshare/hydroshare/static/media /tmp/media
HERE=$PWD
pushd $PWD
cd /tmp
tar -czf "$HERE/media-hydroshare-`date +"%m-%d-%y"`.tar.gz" media
rm -rf /tmp/media
