#!/bin/sh

# initiates a full build of hydroshare inlcuding hs_base if it does not already exist.

# set current working directory as CWD
CWD=$(pwd)

# get submodules
echo "### get git submodules ###"
git submodule init && git submodule update

# build hs_base if it does not exist
IID=$(docker images | grep hs_base | tr -s ' ' | cut -d ' ' -f 3)
if [ -z $IID ];
    then
        echo "### build hs_base ###"
        pushd $CWD
        cd hs_docker_base
        docker build -t hs_base .
        popd;
    else
        echo "### hs_base already exists ###";
fi

# build docker contaiers defined by fig and bring them up
echo "### build docker containers as defined in fig.yml ###"
fig build
echo "### bring up all docker containers as defined in fig.yml ###"
fig up -d

# load pg.development.sql into postgis database
echo "### load clean pg.development.sql database from the running hydroshare container ###"
CID=$(docker ps -a | grep hydroshare_hydroshare_1 | cut -d ' ' -f 1)
docker exec $CID dropdb -U postgres -h postgis postgres
docker exec $CID createdb -U postgres -h postgis postgres
docker exec $CID psql -U postgres -h postgis -w -c 'create extension postgis;'
docker exec $CID psql -U postgres -h postgis -f pg.development.sql
docker exec $CID python manage.py makemigrations
docker exec $CID python manage.py migrate

echo "### complete ###"