#!/bin/bash

# deploy-hs
# Author: Michael Stealey <michael.j.stealey@gmail.com>

echo "*** deploy-hs has been replaced by hsctl ***"
echo ""
echo "  - Update config/hydroshare-config.yaml to match your environment, then use ./hsctl [option]"
echo ""
./hsctl --help
exit 1;
