FROM transloadit/companion

USER root:root 

RUN addgroup --gid 10000 service-accounts 
RUN adduser -u 20028 -s /bin/sh -D -H -g 'hydroshare user' hydro-service service-accounts

# COPY init-uppy /init-uppy
# RUN chown node:node /init-uppy
RUN mkdir /uppy_tmp
RUN chmod 777 /uppy_tmp
RUN chown node:node /uppy_tmp

WORKDIR /app

# RUN npm init -y 
# RUN npm install express 
# RUN npm install @uppy/companion

COPY uppy/server.js /app/server.js
RUN chown node:node /app/server.js

# run daemon
ENTRYPOINT [ ]
CMD "node /app/server.js"
