FROM hydroshare/hs_docker_base:release-1.9.1
MAINTAINER Phuong Doan pdoan@cuahsi.org

# inplaceedit in pip doesn't seem compatible with Django 1.11 yet...
RUN pip install git+https://github.com/theromis/django-inplaceedit.git@e6fa12355defedf769a5f06edc8fc079a6e982ec

USER root
WORKDIR /hydroshare

## Note Begin: these lines were being run in init-hydroshare.template / shell:
#sleep 3s
#cp /hydroshare/hydroshare.conf /etc/supervisor/conf.d/hydroshare.conf
#usermod -u HS_SERVICE_UID hydro-service
#groupmod -g HS_SERVICE_GID storage-hydro
#chown -R hydro-service:storage-hydro /etc/ssh
#chown -R hydro-service:storage-hydro /hs_tmp
#chown -R hydro-service:storage-hydro /shared_tmp
#sed -i "/\<UsePrivilegeSeparation\>/c\UsePrivilegeSeparation no" /etc/ssh/sshd_config
#sed -i "/\<Port 22\>/c\Port 2022" /etc/ssh/sshd_config
#HS_SSH_SERVER
#HS_DJANGO_SERVER
## Note End

# docker exec hydroshare chown -R hydro-service:storage-hydro /hydroshare /tmp /shared_tmp
RUN usermod -u 1000 hydro-service
RUN groupmod -g 1000 storage-hydro
RUN mkdir /hs_tmp
RUN mkdir /shared_tmp
RUN chown -R hydro-service:storage-hydro /hydroshare
RUN chown -R hydro-service:storage-hydro /hs_tmp
RUN chown -R hydro-service:storage-hydro /shared_tmp

CMD ["runuser", "-p", "-u", "hydro-service", "-g", "storage-hydro", "python", "manage.py", "runserver", "0.0.0.0:8000"]
