FROM postgres:9.4.7

ADD ./conf_postgres/pg.development.sql /app/pg.development.sql
ADD ./conf_postgres/pg_hba.conf /app/pg_hba.conf
ADD ./conf_postgres/postgresql.conf /app/postgresql.conf

RUN mkdir -p /app
RUN apt-get update && apt-get install -y \
    sudo \
    wget
RUN sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt trusty-pgdg main" >> /etc/apt/sources.list'
RUN wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
RUN apt-get update && apt-get install -y \
    postgresql-9.4-postgis-2.1 \
    pgadmin3 \
    postgresql-contrib-9.4
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN cp /docker-entrypoint.sh /usr/local/bin/

# TODO bunch of things that don't work:
#RUN echo "listen_addresses = '*' >> /var/lib/postgresql/data/postgresql.conf"

#RUN yes | cp -f /app/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
#RUN yes | cp -f /app/postgresql.conf /var/lib/postgresql/data/postgresql.conf

#RUN chmod 700 /var/lib/postgresql/data
#RUN chown -R postgres /var/lib/postgresql/data

#EXPOSE 5432
#ENTRYPOINT ["docker-entrypoint.sh"]

#USER postgres
#
#CMD ["/usr/lib/postgresql/9.4/bin/postgres", "-c", "config_file=/app/postgresql.conf"]
