postgis:
  image: mjstealey/postgresql
redis:
  image: redis:2.8.19
rabbitmq: 
  image: rabbitmq:3.4.4
hydroshare:
  build: .
  environment:
    POSTGIS_HOST: postgis
    POSTGIS_PORT: 5432
    REDIS_HOST: redis
    REDIS_PORT: 6379
    POSTGIS_PASSWORD: postgres
    POSTGIS_DB: postgres
    POSTGIS_USER: postgres
    PGPASSWORD: postgres
  volumes:
    # Use when NOT sharing the entire host hydroshare directory
    #- "media:/home/docker/hydroshare/hydroshare/static/media"
    # for VM
    # Specific to hydro user on the hydrodev Xubuntu VM
    - "/home/hydro/hydroshare:/home/docker/hydroshare"
    # Specific to hydro user for pycharm debugging on hydrodev Xubuntu VM
    # - "/home/hydro/pycharm-debug:/home/docker/pycharm-debug"
  ports:
    - "1338:22"
    - "8000:8000"
  links:
    - postgis:postgis
    - redis:redis
    - rabbitmq:rabbitmq
  command: /bin/bash init
defaultworker:
  build: .
  environment:
    POSTGIS_HOST: postgis
    POSTGIS_PORT: 5432
    REDIS_HOST: redis
    REDIS_PORT: 6379
    POSTGIS_PASSWORD: postgres
    POSTGIS_DB: postgres
    PGPASSWORD: postgres
    C_FORCE_ROOT: 1
  volumes_from:
    - hydroshare
  volumes:
    - "/var/run/docker.sock:/docker.sock"
  links:
    - postgis:postgis
    - redis:redis
    - rabbitmq:rabbitmq
  command: celery worker -A hydroshare -E -Q default
dockerworker:
  build: .
  environment:
    POSTGIS_HOST: postgis
    POSTGIS_PORT: 5432
    REDIS_HOST: redis
    REDIS_PORT: 6379
    POSTGIS_PASSWORD: postgres
    POSTGIS_DB: postgres
    PGPASSWORD: postgres
    C_FORCE_ROOT: 1
  volumes_from:
    - hydroshare
  volumes:
    - "/var/run/docker.sock:/docker.sock"
  links:
    - postgis:postgis
    - redis:redis
    - rabbitmq:rabbitmq
  command: celery worker -A hydroshare -E -Q docker_container_tasks,docker_broadcast_tasks
