FROM hydroshare/hs_docker_base:release-1.9.7
MAINTAINER Phuong Doan pdoan@cuahsi.org

# inplaceedit in pip doesn't seem compatible with Django 1.11 yet...
RUN pip install git+https://github.com/theromis/django-inplaceedit.git@e6fa12355defedf769a5f06edc8fc079a6e982ec

USER root
WORKDIR /hydroshare

RUN userdel hydro-service \
 && groupdel storage-hydro \
 && echo "storage-hydro:x:HS_SERVICE_GID:" >> /etc/group \
 && echo "hydro-service:x:HS_SERVICE_UID:HS_SERVICE_GID::/hydroshare:/bin/bash" >> /etc/passwd

RUN celery beat -A hydroshare -s /log/celerybeat-schedule &
CMD celery worker -A hydroshare -E -Q default
