
RUN userdel hydro-service \
 && groupdel storage-hydro \
 && echo "storage-hydro:x:HS_SERVICE_GID:" >> /etc/group \
 && echo "hydro-service:x:HS_SERVICE_UID:HS_SERVICE_GID::/hydroshare:/bin/bash" >> /etc/passwd \
 && mkdir /hs_tmp /shared_tmp \
 && chown -R hydro-service:storage-hydro /hydroshare /hs_tmp /shared_tmp

CMD ["runuser", "-p", "-u", "hydro-service", "-g", "storage-hydro", "python", "manage.py", "runserver", "0.0.0.0:8000"]
