FROM solr:6.6

WORKDIR /opt/solr

USER $SOLR_USER

RUN chown -R $SOLR_USER:$SOLR_GROUP /opt/solr
RUN ["mkdir", "/opt/solr/server/solr/collection1"]
RUN ["mkdir", "/opt/solr/server/solr/collection1/conf"]
RUN ["mkdir", "/opt/solr/server/solr/index"]

# TODO Is a reload required here?
RUN rm /opt/solr/server/solr/collection1/conf/managed-schema

ADD ./solr/core.properties /opt/solr/server/solr/collection1/core.properties
ADD ./solr/schema.xml /opt/solr/server/solr/collection1/schema.xml
ADD ./solr/solrconfig.xml /opt/solr/server/solr/collection1/conf/solrconfig.xml

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["solr-foreground"]
