FROM mjstealey/docker-irods-icat:4.1.8

# TODO verify ADD overwrites when no flags provided

#RUN apt-get update && apt-get install -y

ADD ./conf_irods/data.local.org/database_config.json /etc/irods/database_config.json
ADD ./conf_irods/data.local.org/server_config.json /etc/irods/server_config.json
ADD ./conf_irods/service_account.config /etc/irods/service_account.config
ADD ./conf_irods/data.local.org/irods.config /irods.config

ADD ./conf_irods/.pgpass /var/lib/irods/.pgpass
ADD ./conf_irods/data.local.org/.odbc.ini /var/lib/irods/.odbc.ini
ADD ./conf_irods/data.local.org/irods_environment.json /var/lib/irods/.irods/irods_environment.json

#USER root
# TODO reduce permissions after cleaner solution found
RUN chmod -R 777 /var/lib/irods/iRODS/server/log
RUN chmod -R 777 /etc/irods
RUN chmod -R 777 /var/lib/irods
#
#RUN cp /irods-docker-entrypoint.sh /usr/local/bin/
#ENTRYPOINT ["irods-docker-entrypoint.sh"]

#USER irods

# TODO cp create_user.sh delete_user.sh /home/hsuserproxy


#CMD ["/var/lib/irods/iRODS/irodsctl", "start"]
#CMD ["/bin/bash"]

ENTRYPOINT ["/irods-docker-entrypoint.sh"]
CMD ["/bin/bash"]


#Traceback (most recent call last):
#  File "/var/lib/irods/iRODS/scripts/python/get_db_schema_version.py", line 75, in <module>
#    cfg = server_config.ServerConfig()
#  File "/var/lib/irods/packaging/server_config.py", line 56, in __init__
#    self.capture(os.path.join(os.environ['HOME'], '.odbc.ini'), '=')
#  File "/var/lib/irods/packaging/server_config.py", line 67, in capture
#    update = load_odbc_ini(cfg_file)
#  File "/var/lib/irods/packaging/server_config.py", line 27, in load_odbc_ini
#    with open(filename, 'r') as f:
#IOError: [Errno 2] No such file or directory: '/var/lib/irods/.odbc.ini'
#Confirming catalog_schema_version... Success
#ERROR: Validation Failed for [/var/lib/irods/.irods/irods_environment.json]
#     : against [https://schemas.irods.org/configuration/v2/service_account_environment.json]
#  IOError: [Errno 2] No such file or directory: '/var/lib/irods/.irods/irods_environment.json'