
RUN usermod -u {HS_SERVICE_UID} hydro-service
RUN groupmod -g {HS_SERVICE_GID} storage-hydro
RUN mkdir /hs_tmp
RUN mkdir /shared_tmp
RUN chown -R hydro-service:storage-hydro /hydroshare
RUN chown -R hydro-service:storage-hydro /hs_tmp
RUN chown -R hydro-service:storage-hydro /shared_tmp

CMD ["runuser", "-p", "-u", "hydro-service", "-g", "storage-hydro", "python", "manage.py", "runserver", "0.0.0.0:8000"]
