FROM transloadit/companion

USER root:root 

RUN addgroup --gid HS_SERVICE_GID service-accounts 
RUN adduser -u HS_SERVICE_UID -s /bin/sh -D -H -g 'hydroshare user' hydro-service service-accounts

COPY init-uppy /init-uppy
RUN chown hydro-service:service-accounts /init-uppy

# run daemon
ENTRYPOINT [ ]
CMD "sh -c /init-uppy"
