version: '3'
#TODO clocks and timezones
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile-postgis
    container_name: postgis
    hostname: postgis
    volumes:
      - "./.pgdata:/var/lib/postgresql/data"
    ports:
      - "54322:5432"
    stdin_open: true
    tty: true
  redis:
    image: redis:2.8
    container_name: redis
    stdin_open: true
    tty: true
  solr:
    build:
      context: .
      dockerfile: Dockerfile-solr
    container_name: solr
    hostname: solr
    ports:
      - "8983:8983"
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
  hydroshare:
    build:
      context: .
      dockerfile: Dockerfile-hydroshare
    container_name: hydroshare
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    privileged: true
    environment:
      POSTGIS_HOST: postgis
      POSTGIS_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      TMP: /hs_tmp
      POSTGIS_PORT_5432_TCP_ADDR: postgis
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
    volumes:
      # hydroshare repository
      - ".:/hydroshare"
      # log files
      - "${LOGDIR}:/hydroshare/log"
      # shared location for gunicorn.sock between containers
      - "/hs_tmp"
      # temp directory shared with celery workers
      - "/shared_tmp"
      ## Large File download support (two lines below):
      #- "/irods/hydroshare:/irods/hydroshare"
      #- "/irods/hydroshare_vault:/irods/hydroshare_vault"
    ports:
      - "1338:2022"
      - "8000:8000"
      - "15001:15001"
    links:
      - postgis:postgis
      - redis:redis
      - solr:solr
    # TODO wait for service not container. postgres needs to be up and ready
    depends_on:
      - postgis
      - redis
      - solr
    stdin_open: true
    tty: true
  defaultworker:
    # TODO https://docs.docker.com/compose/startup-order/
    build:
      context: .
      dockerfile: Dockerfile-defaultworker
    container_name: defaultworker
    hostname: defaultworker
    environment:
      POSTGIS_HOST: postgis
      POSTGIS_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      PGPASSWORD: postgres
      C_FORCE_ROOT: 1
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      POSTGIS_PORT_5432_TCP_ADDR: postgis
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
    volumes:
      - ".:/hydroshare"
      - "${LOGDIR}:/hydroshare/log"
    links:
      - postgis:postgis
      - redis:redis
    depends_on:
      - hydroshare
      - postgis
      - solr
      - redis
    stdin_open: true
    tty: true
