FROM tusproject/tusd:latest

USER root:root 

RUN addgroup --gid 10000 service-accounts 
RUN adduser -u 20028 -s /bin/sh -D -H -g 'hydroshare user' hydro-service service-accounts

# It is important that tusd operate as hydro-service:service-accounts. 
# Thus all should be owned by those accounts. 
RUN chown hydro-service:service-accounts /srv/tusd-data \
 && mkdir -p /srv/tusd-hooks \
 && chown hydro-service:service-accounts /srv/tusd-hooks \
 && mkdir -p /tusd_tmp \
 && chown hydro-service:service-accounts /tusd_tmp

COPY init-tusd /init-tusd
RUN chown hydro-service:service-accounts /init-tusd

# run daemon
ENTRYPOINT [ ]
CMD /init-tusd
