FROM hydroshare/hs-irods:2e7929c

RUN mkdir -p /home/hsuserproxy/.irods
COPY ./irods/delete_user.sh /home/hsuserproxy/delete_user.sh
COPY ./irods/create_user.sh /home/hsuserproxy/create_user.sh

RUN chown -R hsuserproxy:hsuserproxy /home/hsuserproxy

RUN apt-get update \
  && apt-get install -y openssh-server \
  && mkdir /var/run/sshd \
  && /etc/init.d/ssh restart

ENTRYPOINT chown -R hsuserproxy:hsuserproxy /home/hsuserproxy && service ssh restart && /irods-docker-entrypoint.sh