FROM postgres:9.4.7

#WORKDIR /app

ADD pg.development.sql /app/pg.development.sql


#TODO when mkdir use -p to be more reliable
RUN mkdir -p /app
RUN apt-get update && apt-get install -y \
    sudo \
    wget
RUN sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt trusty-pgdg main" >> /etc/apt/sources.list'
RUN wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
RUN apt-get update && apt-get install -y \
    postgresql-9.4-postgis-2.1 \
    pgadmin3 \
    postgresql-contrib-9.4
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
#RUN useradd postgres
RUN chown -R postgres /var/lib/postgresql/data


#TODO this is broken
#RUN echo "listen_addresses = '*' >> /var/lib/postgresql/data/postgresql.conf"






#RUN psql -U postgres -f /app/pg.development.sql

#RUN cp /docker-entrypoint.sh /usr/local/bin/

#EXPOSE 5432
#ENTRYPOINT ["docker-entrypoint.sh"]


#CMD ["postgres"]



#WARNING: enabling "trust" authentication for local connections
#You can change this by editing pg_hba.conf or using the option -A, or
#--auth-local and --auth-host, the next time you run initdb.





#RUN echo "listen_addresses = '*'" >> /var/lib/postgresql/data/postgresql.conf




#ENTRYPOINT ["/docker-entrypoint.sh"]
#
#EXPOSE 5432
#CMD ["postgres"]