FROM hydroshare/tusd:latest

USER root:root 

COPY init-tusd /init-tusd
RUN chown tusd:tusd /init-tusd

COPY tusd/hooks/* /srv/tusd-hooks
RUN chown tusd:tusd /srv/tusd-hooks/*

# run daemon
CMD /bin/bash
