FROM hydroshare/hs_docker_base:release-1.9.7
MAINTAINER Phuong Doan pdoan@cuahsi.org

# inplaceedit in pip doesn't seem compatible with Django 1.11 yet...
RUN pip install git+https://github.com/theromis/django-inplaceedit.git@e6fa12355defedf769a5f06edc8fc079a6e982ec

USER root
WORKDIR /hydroshare


RUN userdel hydro-service \
 && groupdel storage-hydro \
 && echo "storage-hydro:x:214400513:" >> /etc/group \
 && echo "hydro-service:x:214401701:214400513::/hydroshare:/bin/bash" >> /etc/passwd

COPY hydroshare.conf /etc/supervisor/conf.d/hydroshare.conf
RUN mkdir /hs_tmp /shared_tmp \
 && chown -R hydro-service:storage-hydro /hydroshare /hs_tmp /shared_tmp /tmp \
 && setfacl -R -m d:g:storage-hydro:rwx /tmp \
 && setfacl -R -m g:storage-hydro:rwx /tmp

CMD ["runuser", "-p", "-u", "root", "-g", "root", "supervisord", "-n"]
#CMD ["runuser", "-p", "-u", "root", "-g", "storage-hydro", "python", "manage.py", "runserver", "0.0.0.0:8000"]
