FROM node:14.14.0 as node-build

ADD . /hydroshare

WORKDIR /hydroshare/hs_discover

RUN rm -rf static templates && \
    mkdir static templates && \
    mkdir templates/hs_discover && \
    mkdir static/js && \
    mkdir static/css && \
    npm install && \
    npm run build && \
    mkdir -p static/js && \
    mkdir -p static/css && \
    cp -rp templates/hs_discover/js static/ && \
    cp -rp templates/hs_discover/css static/ && \
    cp -p templates/hs_discover/map.js static/js/ && \
    echo "----------------js--------------------" && \
    ls -l static/js && \
    echo "--------------------------------------" && \
    echo "----------------css-------------------" && \
    ls -l static/css && \
    echo "--------------------------------------"

FROM hydroshare/hs_docker_base:a73451a

COPY --from=node-build /hydroshare /hydroshare

# Set the locale. TODO - remove once we have a better alternative worked out
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

RUN curl https://dl.min.io/client/mc/release/linux-amd64/mc \
    --create-dirs \
    -o $HOME/minio-binaries/mc
RUN mv $HOME/minio-binaries/mc /usr/local/bin/mc
RUN chmod +x /usr/local/bin/mc

RUN apt-get update
RUN apt-get -y upgrade
RUN curl -1sLf 'https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.deb.sh' | bash
RUN apt install -y redpanda-rpk redpanda-connect jq

RUN pip install redpanda-connect

RUN pip install confluent-kafka

RUN pip install pymongo

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

USER root
WORKDIR /hydroshare

CMD ["/bin/bash"]
