FROM mjstealey/docker-irods-icat:4.1.8

ADD ./irods/delete_user.sh /home/hsuserproxy
ADD ./irods/delete_user.sh /home/hsuserproxy
RUN useradd -m -p hsuserproxy -s /bin/bash hsuserproxy

RUN chmod -R 777 /home
