#!/usr/bin/env bash


#git submodule init && git submodule update


docker exec hydroshare chown -R hydro-service:storage-hydro /hydroshare /tmp /shared_tmp
docker exec -u hydro-service hydroshare python manage.py collectstatic -v0 --noinput
docker exec -u hydro-service hydroshare rm -f hydroshare/static/robots.txt
docker restart hydroshare


docker exec postgis psql -U postgres -c "REVOKE CONNECT ON DATABASE postgres FROM public;"
docker exec postgis psql -U postgres -c "SELECT pid, pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = current_database() AND pid <> pg_backend_pid();"
docker exec postgis dropdb -U postgres postgres

docker exec -u hydro-service hydroshare psql -U postgres -h postgis -d template1 -w -c 'CREATE EXTENSION postgis;'
docker exec -u hydro-service hydroshare psql -U postgres -h postgis -d template1 -w -c 'CREATE EXTENSION hstore;'

docker exec -u hydro-service hydroshare createdb -U postgres -h postgis postgres --encoding UNICODE --template=template1
docker exec -u hydro-service hydroshare psql -U postgres -h postgis -d postgres -w -c 'SET client_min_messages TO WARNING;'
docker exec -u hydro-service hydroshare psql -U postgres -h postgis -d postgres -q -f pg.development.sql


docker exec -u hydro-service hydroshare python manage.py migrate sites --noinput
docker exec -u hydro-service hydroshare python manage.py migrate --fake-initial --noinput
docker exec -u hydro-service hydroshare python manage.py fix_permissions


docker exec solr bin/solr create -c collection1 -d basic_configs
docker exec hydroshare python manage.py build_solr_schema -f schema.xml
sleep 1s
docker exec solr cp /hydroshare/schema.xml /opt/solr/server/solr/collection1/conf/schema.xml


docker exec solr sed -i '/<schemaFactory class="ManagedIndexSchemaFactory">/,+4d' /opt/solr/server/solr/collection1/conf/solrconfig.xml
docker exec solr rm /opt/solr/server/solr/collection1/conf/managed-schema
docker exec hydroshare curl "solr:8983/solr/admin/cores?action=RELOAD&core=collection1"
docker exec hydroshare python manage.py rebuild_index --noinput
