#! /bin/sh
 
# REQUIRED ENVIRONMENT VARIABLES 
# any long set of random characters for the server session
export COMPANION_SECRET="h3h5872hgtF0374829371859ntirbeow"
# specifying a secret file will override a directly set secret
### export COMPANION_SECRET_FILE="PATH/TO/COMPANION/SECRET/FILE"
# corresponds to the server.host option
export COMPANION_DOMAIN="cuahsi-dev-1.hydroshare.org"
# corresponds to the filePath option
# separate folder, as companion and tusd aren't designed to share files. 
export COMPANION_DATADIR="/uppy_tmp" 

# ###### Optional variables ##########

# corresponds to the server.protocol option, defaults to http
export COMPANION_PROTOCOL="https"
# the port on which to start the server, defaults to 3020
export COMPANION_PORT=3020
# corresponds to the server.path option, defaults to ''. 
export COMPANION_PATH="/companion/"
# disables the welcome page, defaults to false
### export COMPANION_HIDE_WELCOME="true"
# disables the metrics page, defaults to false
### export COMPANION_HIDE_METRICS="true"
  
# use this in place of COMPANION_PATH if the server path should not be
# handled by the express.js app, but maybe by an external server configuration
# instead (e.g Nginx).
# export COMPANION_IMPLICIT_PATH="/companion/"

# # corresponds to the corsOrigins option, but can contain a comma-separated list of String values.
# # if neither this or COMPANION_CLIENT_ORIGINS_REGEX specified, the server would allow any host
# ### COMPANION_CLIENT_ORIGINS="http://localhost:3452,https://uppy.io"
# 
# # Like COMPANION_CLIENT_ORIGINS, but allows a single regex instead
# # (COMPANION_CLIENT_ORIGINS will be ignored if this is used and vice versa)
# ### COMPANION_CLIENT_ORIGINS_REGEX="https://.*\.example\.(com|eu)$"
  
# to enable Dropbox
export COMPANION_DROPBOX_KEY="07xw8rzny3rgkno"
export COMPANION_DROPBOX_SECRET="7an6hhingzaqgif"
 
# to enable Box
COMPANION_BOX_KEY="rv3q3tz9cq7995uaguahjvc9m524uhso"
COMPANION_BOX_SECRET="PupcsbgEtWblcIk9TiELudGpxXB3zbvD"
# specifying a secret file will override a directly set secret
### export COMPANION_BOX_SECRET_FILE="PATH/TO/BOX/SECRET/FILE"
 
# to enable Google Drive
export COMPANION_GOOGLE_KEY="876543925663-7v2tf3dg8p9nugtjtcm37ks8ckub8cf4.apps.googleusercontent.com"
export COMPANION_GOOGLE_SECRET="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"

# to enable Onedrive
### export COMPANION_ONEDRIVE_KEY="YOUR ONEDRIVE KEY"
### export COMPANION_ONEDRIVE_SECRET="YOUR ONEDRIVE SECRET"
# specifying a secret file will override a directly set secret
### export COMPANION_ONEDRIVE_SECRET_FILE="PATH/TO/ONEDRIVE/SECRET/FILE"
  
# to enable S3
### export COMPANION_AWS_KEY="YOUR AWS KEY"
### export COMPANION_AWS_SECRET="YOUR AWS SECRET"
# specifying a secret file will override a directly set secret
### export COMPANION_AWS_SECRET_FILE="PATH/TO/AWS/SECRET/FILE"
### export COMPANION_AWS_BUCKET="YOUR AWS S3 BUCKET"
### export COMPANION_AWS_REGION="AWS REGION"
# to enable S3 Transfer Acceleration (default: false)
### export COMPANION_AWS_USE_ACCELERATE_ENDPOINT="false"
# to set X-Amz-Expires query param in presigned urls (in seconds, default: 300)
### export COMPANION_AWS_EXPIRES="300"
# to set a canned ACL for uploaded objects: https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl
### export COMPANION_AWS_ACL="public-read"
 
# corresponds to the server.oauthDomain option
### export COMPANION_OAUTH_DOMAIN="sub.domain.com"
# corresponds to the server.validHosts option
### export COMPANION_DOMAINS="sub1.domain.com,sub2.domain.com,sub3.domain.com"
  
# corresponds to the sendSelfEndpoint option
export COMPANION_SELF_ENDPOINT="https://cuahsi-dev-1.hydroshare.org/companion/"
  
# comma-separated URLs
# corresponds to the uploadUrls option (comma-separated)
### export COMPANION_UPLOAD_URLS="http://tusd.tusdemo.net/files/,https://tusd.tusdemo.net/files/"
  
# corresponds to the streamingUpload option
export COMPANION_STREAMING_UPLOAD=false
  
# corresponds to the allowLocalUrls option
export COMPANION_ALLOW_LOCAL_URLS=true
  
# corresponds to the maxFileSize option
export COMPANION_MAX_FILE_SIZE="1000000"

node /app/bin/companion --config /options-uppy.json
