#!/bin/bash

# ##########################################################
# this file should be called after the init_github, and init_modules scripts. #
# ##########################################################

# docker init file. This will bring up all the services: celery, uwsgi, sshd, and nginx
service nginx restart
/usr/sbin/sshd

cd /home/docker/hydroshare
su docker -c "python manage.py syncdb"
su docker -c "python manage.py migrate"
su docker -c "python manage.py collectstatic --noinput"
export PYTHONPATH=/home/docker/hydroshare
python manage.py runserver 0.0.0.0:8000