services:
  minio:
    # this is the last release before the admin features were removed from the console
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    platform: linux/amd64
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
      - "9001"
    volumes:
      - minio_data_vol:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT: "false"
      MINIO_SCANNER_SPEED: "fastest"
      MINIO_POLICY_PLUGIN_URL: "http://micro-auth/minio/authorization/"
      MINIO_NOTIFY_KAFKA_ENABLE_RESOURCEFILE: "on"
      MINIO_NOTIFY_KAFKA_BROKERS_RESOURCEFILE: "redpanda:9092"
      MINIO_NOTIFY_KAFKA_TOPIC_RESOURCEFILE: "resource_file"
      # mc event add hydroshare/admin arn:minio:sqs::RESOURCEFILE:kafka --event put,delete
    command: server --console-address ":9001" /data
    depends_on:
      - micro-auth
  postgis:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: 'postgres'
    container_name: postgis
    hostname: postgis
    volumes:
      - "postgis_data_vol:/var/lib/postgresql/data"
    ports:
      - "54322:5432"
    stdin_open: true
    tty: true
  pgbouncer:
    image: edoburu/pgbouncer:latest
    platform: linux/amd64
    container_name: pgbouncer
    environment:
      DB_HOST: postgis
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_PORT: 5432
      LISTEN_ADDR: "*"
      LISTEN_PORT: 6432
      POOL_MODE: "transaction"
      AUTH_TYPE: "plain"
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 5
      MIN_POOL_SIZE: 2
    ports:
      - "6432:6432"
    depends_on:
      - postgis
  redpanda:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      # Address the broker advertises to clients that connect to the Kafka API.
      # Use the internal addresses to connect to the Redpanda brokers'
      # from inside the same Docker network.
      # Use the external addresses to connect to the Redpanda brokers'
      # from outside the Docker network.
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      # Mode dev-container uses well-known configuration properties for development in containers.
      - --mode dev-container
      # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.2.5
    container_name: redpanda
    volumes:
      - redpanda_data_vol:/var/lib/redpanda/data
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
  redpanda-console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v3.2.2
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda
  solr:
    image: solr:6.6
    platform: linux/amd64
    container_name: solr
    volumes:
      # hydroshare repository
      - ".:/hydroshare"
      - "solr_data_vol:/opt/solr/server/solr"
    ports:
      - "8983"
    command: ["solr-foreground"]
  hydroshare:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hydroshare
    hostname: hydroshare
    devices:
      - "/dev/fuse"
    privileged: true
    environment:
      POSTGIS_HOST: pgbouncer
      POSTGIS_PORT: 6432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      TMP: /tmp
      POSTGIS_PORT_5432_TCP_ADDR: pgbouncer
      POSTGIS_DISABLE_SERVER_SIDE_CURSORS: "True"
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
      VUE_APP_BUCKET_URL_PUBLIC_PATH: "/static/static"
      MC_HOST_hydroshare: "http://minioadmin:minioadmin@minio:9000"
    volumes:
      # hydroshare repository
      - ".:/hydroshare"
      # shared location for gunicorn.sock between containers
      - "temp_vol:/tmp"
      # temp directory shared with celery workers
      - "share_vol:/shared_tmp"
    ports:
      - "1338:2022"
      - "8000:8000"
    links:
      - postgis:postgis
      - solr:solr
      - redpanda:redpanda
      - minio:minio
    depends_on:
      - postgis
      - pgbouncer
      - solr
      - redpanda
      - minio
      - redis
    stdin_open: true
    tty: true
    command: /bin/bash init-hydroshare
  defaultworker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: defaultworker
    platform: linux/amd64
    hostname: defaultworker
    environment:
      POSTGIS_HOST: pgbouncer
      POSTGIS_PORT: 6432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      C_FORCE_ROOT: 1
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      POSTGIS_PORT_5432_TCP_ADDR: pgbouncer
      POSTGIS_DISABLE_SERVER_SIDE_CURSORS: "True"
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
      COLUMNS: 80
      MC_HOST_hydroshare: "http://minioadmin:minioadmin@minio:9000"
    ports:
      - "5555:5555"
    volumes:
      - ".:/hydroshare"
    links:
      - pgbouncer:pgbouncer
      - redpanda:redpanda
    depends_on:
      - hydroshare
      - pgbouncer
      - solr
      - redpanda
    stdin_open: true
    tty: true
    command: /bin/bash init-defaultworker
  companion:
  # https://github.com/transloadit/uppy/blob/main/packages/%40uppy/companion/KUBERNETES.md
    image:  docker.io/transloadit/companion:5.5.0
    platform: linux/amd64
    container_name: companion
    hostname: companion
    environment:
      COMPANION_PORT: '3020'
      COMPANION_CLIENT_ORIGINS: 'https://localhost'
      # when testing 3rd party services like google drive, you will access hydroshare at http://host.docker.internal:8000
      # you will need to add a line in your /etc/hosts file to map host.docker.internal to localhost
      COMPANION_UPLOAD_URLS: 'https://localhost/django_s3/tus/*'
      COMPANION_DATADIR: '/mnt/companion-data'
      COMPANION_DOMAIN: 'localhost'
      COMPANION_PATH: '/companion'
      COMPANION_ALLOW_LOCAL_URLS: 'true'
      COMPANION_PROTOCOL: 'https'
      COMPANION_REDIS_URL: 'redis://redis:6379'
      COMPANION_CHUNK_SIZE: '100000000'  # ~72MB
      # COMPANION_PREAUTH_SECRET: 'another secret'
      # For 3rd party services like google drive to work locally, you need to set the following:
      COMPANION_SECRET: 'SECRET'
      # Intentionally added to repo for testing purposes
      COMPANION_GOOGLE_KEY: '737951655407-p3d2b2bl2ln90g5plfj09e98bprk42da.apps.googleusercontent.com'
      COMPANION_GOOGLE_SECRET: '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'
      # https://uppy.io/docs/companion/#enablegooglepickerendpoint-companion_enable_google_picker_endpoint
      COMPANION_ENABLE_GOOGLE_PICKER_ENDPOINT: 'true'
    ports:
      - "3020:3020"
    volumes:
      - "companion_vol:/mnt/companion-data"
    depends_on:
      - redis
  redis:
    image: redis:latest
    platform: linux/amd64
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - "redis_data_vol:/data"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-local-dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/ssl
    depends_on:
      - hydroshare
      - companion
  micro-auth:
    image: hydroshare/micro-auth:latest
    platform: linux/amd64
    container_name: micro-auth
    environment:
      HS_DATABASE_URL: "postgresql://postgres:postgres@postgis:5432/postgres"
      MC_HOST_hydroshare: "http://minioadmin:minioadmin@minio:9000"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - 8001:8001
    links:
      - postgis:postgis
    restart: on-failure
    depends_on:
      - postgis
  hsextract:
    image: hydroshare/hsextract:0.11.37
    platform: linux/amd64
    links:
      - redpanda:redpanda
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_S3_ENDPOINT=http://minio:9000
volumes:
  postgis_data_vol:
  solr_data_vol:
  temp_vol:
  share_vol:
  redpanda_data_vol:
  minio_data_vol:
  redis_data_vol:
  companion_vol: