version: '3'
services:
  minio:
    image: minio/minio
    platform: linux/amd64
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
      - "9001"
    volumes:
      - minio_data_vol:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
  postgis:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: 'postgres'
    container_name: postgis
    hostname: postgis
    volumes:
      - "postgis_data_vol:/var/lib/postgresql/data"
    ports:
      - "54322:5432"
    stdin_open: true
    tty: true
  pgbouncer:
    image: edoburu/pgbouncer:latest
    platform: linux/amd64
    container_name: pgbouncer
    environment:
      DB_HOST: postgis
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_PORT: 5432
      LISTEN_ADDR: "*"
      LISTEN_PORT: 6432
      POOL_MODE: "transaction"
      AUTH_TYPE: "plain"
      MAX_CLIENT_CONN: 10
      DEFAULT_POOL_SIZE: 5
      MIN_POOL_SIZE: 2
    ports:
      - "6432:6432"
    depends_on:
      - postgis
  rabbitmq:
    image: rabbitmq:3.8.2
    platform: linux/amd64
    container_name: rabbitmq
    volumes:
      - "rabbitmq_data_vol:/var/lib/rabbitmq"
  solr:
    image: solr:6.6
    platform: linux/amd64
    container_name: solr
    volumes:
      # hydroshare repository
      - ".:/hydroshare"
      - "solr_data_vol:/opt/solr/server/solr"
    ports:
      - "8983"
    command: ["solr-foreground"]
  hydroshare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hydroshare
    hostname: hydroshare
    platform: linux/amd64
    devices:
      - "/dev/fuse"
    privileged: true
    environment:
      POSTGIS_HOST: pgbouncer
      POSTGIS_PORT: 6432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      RABBITMQ_PORT_5672_TCP_ADDR: rabbitmq
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      TMP: /tmp
      POSTGIS_PORT_5432_TCP_ADDR: pgbouncer
      POSTGIS_DISABLE_SERVER_SIDE_CURSORS: True
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
    volumes:
      # hydroshare repository
      - ".:/hydroshare"
      # shared location for gunicorn.sock between containers
      - "temp_vol:/tmp"
      # temp directory shared with celery workers
      - "share_vol:/shared_tmp"
    ports:
      - "1338:2022"
      - "8000:8000"
    links:
      - postgis:postgis
      - solr:solr
      - rabbitmq:rabbitmq
      - minio:minio
    depends_on:
      - postgis
      - pgbouncer
      - solr
      - rabbitmq
      - minio
    stdin_open: true
    tty: true
    command: /bin/bash init-hydroshare
  defaultworker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: defaultworker
    hostname: defaultworker
    platform: linux/amd64
    environment:
      POSTGIS_HOST: pgbouncer
      POSTGIS_PORT: 6432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      C_FORCE_ROOT: 1
      RABBITMQ_PORT_5672_TCP_ADDR: rabbitmq
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      POSTGIS_PORT_5432_TCP_ADDR: postgis
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
      COLUMNS: 80
    ports:
      - "5555:5555"
    volumes:
      - ".:/hydroshare"
    links:
      - pgbouncer:pgbouncer
      - rabbitmq:rabbitmq
    depends_on:
      - hydroshare
      - pgbouncer
      - solr
      - rabbitmq
    stdin_open: true
    tty: true
    command: /bin/bash init-defaultworker
volumes:
  postgis_data_vol:
  solr_data_vol:
  temp_vol:
  share_vol:
  rabbitmq_data_vol:
  minio_data_vol:
