services:
  minio:
    # this is the last release before the admin features were removed from the console
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    platform: linux/amd64
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
      - "9001"
    volumes:
      - minio_data_vol:/data
    environment:
      MINIO_ROOT_USER: cuahsi
      MINIO_ROOT_PASSWORD: devpassword
      MINIO_BROWSER_REDIRECT: "false"
      MINIO_SCANNER_SPEED: "fastest"
      MINIO_POLICY_PLUGIN_URL: "http://micro-auth/minio/authorization/"
      MINIO_NOTIFY_KAFKA_ENABLE_RESOURCEFILE: "on"
      MINIO_NOTIFY_KAFKA_BROKERS_RESOURCEFILE: "redpanda:9092"
      MINIO_NOTIFY_KAFKA_TOPIC_RESOURCEFILE: "resource_file"
    command: server --console-address ":9001" /data
    depends_on:
      - micro-auth
  postgis:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: 'postgres'
    container_name: postgis
    hostname: postgis
    volumes:
      - "postgis_data_vol:/var/lib/postgresql/data"
    ports:
      - "54322:5432"
    stdin_open: true
    tty: true
  pgbouncer:
    image: edoburu/pgbouncer:latest
    platform: linux/amd64
    container_name: pgbouncer
    environment:
      DB_HOST: postgis
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_PORT: 5432
      LISTEN_ADDR: "*"
      LISTEN_PORT: 6432
      POOL_MODE: "transaction"
      AUTH_TYPE: "plain"
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 5
      MIN_POOL_SIZE: 2
    ports:
      - "6432:6432"
    depends_on:
      - postgis
  solr:
    image: solr:6.6
    platform: linux/amd64
    container_name: solr
    volumes:
      # hydroshare repository
      - ".:/hydroshare"
      - "solr_data_vol:/opt/solr/server/solr"
    ports:
      - "8983"
    command: ["solr-foreground"]
  hydroshare:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hydroshare
    hostname: hydroshare
    devices:
      - "/dev/fuse"
    privileged: true
    environment:
      POSTGIS_HOST: pgbouncer
      POSTGIS_PORT: 6432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      TMP: /tmp
      POSTGIS_PORT_5432_TCP_ADDR: pgbouncer
      POSTGIS_DISABLE_SERVER_SIDE_CURSORS: "True"
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
      VUE_APP_BUCKET_URL_PUBLIC_PATH: "/static/static"
      MC_HOST_hydroshare: "http://cuahsi:devpassword@minio:9000"
      DATACITE_USERNAME: ${DATACITE_USERNAME}
      DATACITE_PASSWORD: ${DATACITE_PASSWORD}
      ATLAS_CONNECTION_URL: "mongodb://user:pass@mongodb:27017/"
      AWS_ENDPOINT_URL: "http://minio:9000"
      AWS_ACCESS_KEY_ID: cuahsi
      AWS_SECRET_ACCESS_KEY: devpassword
    volumes:
      # hydroshare repository
      - ".:/hydroshare"
      # shared location for gunicorn.sock between containers
      - "temp_vol:/tmp"
      # temp directory shared with celery workers
      - "share_vol:/shared_tmp"
    ports:
      - "1338:2022"
      - "8000:8000"
    links:
      - postgis:postgis
      - solr:solr
      - redpanda:redpanda
      - minio:minio
    depends_on:
      - postgis
      - pgbouncer
      - solr
      - redpanda
      - minio
      - redis
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
  defaultworker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: defaultworker
    platform: linux/amd64
    hostname: defaultworker
    environment:
      POSTGIS_HOST: pgbouncer
      POSTGIS_PORT: 6432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      C_FORCE_ROOT: 1
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      POSTGIS_PORT_5432_TCP_ADDR: pgbouncer
      POSTGIS_DISABLE_SERVER_SIDE_CURSORS: "True"
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
      COLUMNS: 80
      MC_HOST_hydroshare: "http://cuahsi:devpassword@minio:9000"
    ports:
      - "5555:5555"
    volumes:
      - ".:/hydroshare"
    links:
      - pgbouncer:pgbouncer
      - redpanda:redpanda
    depends_on:
      - hydroshare
      - pgbouncer
      - solr
      - redpanda
    stdin_open: true
    tty: true
    command: /bin/bash init-defaultworker
  hs_event_s3:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      POSTGIS_HOST: pgbouncer
      POSTGIS_PORT: 6432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      C_FORCE_ROOT: 1
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      POSTGIS_PORT_5432_TCP_ADDR: pgbouncer
      POSTGIS_DISABLE_SERVER_SIDE_CURSORS: "True"
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
      COLUMNS: 80
      MC_HOST_hydroshare: "http://cuahsi:devpassword@minio:9000"
    volumes:
      - ".:/hydroshare"
    links:
      - pgbouncer:pgbouncer
      - redpanda:redpanda
    depends_on:
      - hydroshare
      - pgbouncer
      - solr
      - redpanda
    stdin_open: true
    tty: true
    command:
      - rpk
      - connect
      - run
      - --rpc-plugins=/hydroshare/hs_event_s3/notify_hs_django_plugin.yaml
      - /hydroshare/hs_event_s3/notify_hs_django_pipeline.yaml
  discovery_collection_worker:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      POSTGIS_HOST: pgbouncer
      POSTGIS_PORT: 6432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      C_FORCE_ROOT: 1
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      POSTGIS_PORT_5432_TCP_ADDR: pgbouncer
      POSTGIS_DISABLE_SERVER_SIDE_CURSORS: "True"
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
      COLUMNS: 80
      MC_HOST_hydroshare: "http://cuahsi:devpassword@minio:9000"
      AWS_ENDPOINT_URL: "http://minio:9000"
      AWS_ACCESS_KEY_ID: cuahsi
      AWS_SECRET_ACCESS_KEY: devpassword
      ATLAS_CONNECTION_URL: "mongodb://user:pass@mongodb:27017/"
    volumes:
      - ".:/hydroshare"
    links:
      - pgbouncer:pgbouncer
      - redpanda:redpanda
      - minio:minio
      - mongodb:mongodb
    depends_on:
      - hydroshare
      - pgbouncer
      - solr
      - redpanda
    stdin_open: true
    tty: true
    command:
      - rpk
      - connect
      - run
      - --rpc-plugins=/hydroshare/hs_event_s3/discovery_collection_plugin.yaml
      - /hydroshare/hs_event_s3/discovery_collection_pipeline.yaml
  redpanda:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.2.5
    container_name: redpanda
    volumes:
      - redpanda_data_vol:/var/lib/redpanda/data
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
  redpanda-console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v3.2.2
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda
  hs_extract:
    build:
      context: .
      dockerfile: hs_extract/Dockerfile
    platform: linux/amd64
    environment:
      AWS_S3_ENDPOINT_URL: "http://minio:9000"
      AWS_ACCESS_KEY_ID: cuahsi
      AWS_SECRET_ACCESS_KEY: devpassword
      MC_HOST_hydroshare: "http://cuahsi:devpassword@minio:9000"
    volumes:
      - "./hs_extract:/app/hs_extract"
      - "./hs_cloudnative_schemas:/app/hs_extract/hs_cloudnative_schemas"
    links:
      - pgbouncer:pgbouncer
      - redpanda:redpanda
    depends_on:
      - hydroshare
      - pgbouncer
      - solr
      - redpanda
    stdin_open: true
    tty: true
  companion:
  # https://github.com/transloadit/uppy/blob/main/packages/%40uppy/companion/KUBERNETES.md
    build:
      context: companion
      dockerfile: Dockerfile
    # image: docker.io/transloadit/companion:5.5.0
    platform: linux/amd64
    container_name: companion
    hostname: companion
    environment:
      COMPANION_PORT: '3020'
      # COMPANION_CLIENT_ORIGINS: 'https://localhost,http://localhost:5004'
      COMPANION_CLIENT_ORIGINS: 'http://localhost,http://localhost:5004'
      COMPANION_UPLOAD_URLS: '*localhost*'
      COMPANION_DATADIR: '/mnt/companion-data'
      COMPANION_DOMAIN: 'localhost'
      COMPANION_PATH: '/companion'
      COMPANION_ALLOW_LOCAL_URLS: 'true'
      COMPANION_PROTOCOL: 'http'
      COMPANION_REDIS_URL: 'redis://redis:6379'
      COMPANION_CHUNK_SIZE: '100000000'  # ~72MB
      # COMPANION_PREAUTH_SECRET: 'another secret'
      # For 3rd party services like google drive to work locally, you need to set the following:
      COMPANION_SECRET: 'SECRET'
      # Intentionally added to repo for testing purposes
      COMPANION_GOOGLE_KEY: '737951655407-p3d2b2bl2ln90g5plfj09e98bprk42da.apps.googleusercontent.com'
      COMPANION_GOOGLE_SECRET: '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'
      # https://uppy.io/docs/companion/#enablegooglepickerendpoint-companion_enable_google_picker_endpoint
      COMPANION_ENABLE_GOOGLE_PICKER_ENDPOINT: 'true'
      COMPANION_AWS_FORCE_PATH_STYLE: 'true'
      # the key and secret are now dynamically calculated in companion-custom-s3-client.js
      # COMPANION_AWS_KEY: 'minioadmin'
      # COMPANION_AWS_SECRET: 'minioadmin'
      COMPANION_AWS_ENDPOINT: 'http://host.docker.internal:9000'
      # https://uppy.io/docs/companion/#s3bucket-companion_aws_bucket
      # COMPANION_AWS_BUCKET: asdf2
      # The bucket is now dynamically calculated in companion-custom-config.js, using the upload metadata
      # https://github.com/hydroshare/hydroshare/pull/5974#issuecomment-2963085209
      COMPANION_AWS_REGION: 'us-central-1'
    ports:
      - "3020:3020"
    volumes:
      - "companion_vol:/mnt/companion-data"
    depends_on:
      - redis
  redis:
    image: redis:latest
    platform: linux/amd64
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - "redis_data_vol:/data"
    command: redis-server
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-local-dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/ssl
    depends_on:
      - hydroshare
      - companion
  micro-auth:
    image: hydroshare/micro-auth:latest
    platform: linux/amd64
    container_name: micro-auth
    build:
      context: ./hs_auth_minio
      dockerfile: Dockerfile
    environment:
      HS_DATABASE_URL: "postgresql://postgres:postgres@postgis:5432/postgres"
      MC_HOST_hydroshare: "http://cuahsi:devpassword@minio:9000"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      ENABLE_EDIT_ACTIONS: "true"
    ports:
      - 8001:8001
    links:
      - postgis:postgis
    restart: on-failure
    depends_on:
      - postgis
  mongodb:
    image: mongodb/mongodb-atlas-local
    container_name: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_vol:/data/db
      - mongodb_config_vol:/data/configdb
  # Instead of running the landing page in docker compose, we run it using PM2
  # This is done via "make up-landing"
  # This has the benefit of HMR and other vite dev server features
  # landing-page:
  #   build:
  #     context: landing-page
  #     dockerfile: Dockerfile
  #     args:
  #       - VITE_APP_BASE=/resource/
  #       - VITE_APP_API_URL=POINT_ME_AT_API_URL
  #       - VITE_APP_NAME=hs-landing-page
  #       - VITE_APP_ORIGIN=https://localhost
  #   container_name: landing-page
  #   hostname: landing-page
  #   platform: linux/amd64
  #   environment:
  #     VITE_APP_NAME: "hs-landing-page"
  #     VITE_APP_ORIGIN: "https://localhost"
  #     VITE_APP_BASE: "/resource/"
  #     VITE_APP_API_URL: "POINT_ME_AT_API_URL"
  #   ports:
  #     - "5004:5004"
volumes:
  postgis_data_vol:
  solr_data_vol:
  mongodb_data_vol:
  mongodb_config_vol:
  temp_vol:
  share_vol:
  redpanda_data_vol:
  minio_data_vol:
  redis_data_vol:
  companion_vol:
