version: '3'
services:
  data.local.org:
    image: hydroshare/hs-irods:4.2.6-buster
    container_name: data.local.org
    hostname: data.local.org
    ports:
      - "1247:1247"
    volumes:
      - "idata_iconf_vol:/etc/irods"
      - "idata_vault_vol:/var/lib/irods"
      - "idata_pgres_vol:/var/lib/postgresql/data"
      - "idata_home_vol:/home"
    environment:
      USE_IRODS: 'True'
      IRODS_ROOT: '/tmp'
      IRODS_ICOMMANDS_PATH: '/usr/bin'
      IRODS_HOST: 'data.local.org'
      IRODS_PORT: '1247'
      IRODS_DEFAULT_RESOURCE: 'hydroshareReplResc'
      IRODS_HOME_COLLECTION: '/hydroshareZone/home/wwwHydroProxy'
      IRODS_ZONE: 'hydroshareZone'
      IRODS_USERNAME: 'wwwHydroProxy'
      IRODS_AUTH: 'wwwHydroProxy'
      IRODS_GLOBAL_SESSION: 'True'
      REMOTE_USE_IRODS: 'True'
      IRODS_ZONE_NAME: 'hydroshareZone'
      IRODS_SERVER_ZONE_KEY: 'hydroshareZone_KEY'
      IRODS_DATABASE_SERVER_HOSTNAME: 'data.local.org'
      IRODS_USER_NAME: 'rods'
      IRODS_PASSWORD: 'rods'
    stdin_open: true
    tty: true
  postgis:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_PASSWORD: 'postgres'
    container_name: postgis
    hostname: postgis
    volumes:
      - "postgis_data_vol:/var/lib/postgresql/data"
    ports:
      - "54322:5432"
    stdin_open: true
    tty: true
  rabbitmq:
    image: rabbitmq:3.8.2
    container_name: rabbitmq
    volumes:
      - "rabbitmq_data_vol:/var/lib/rabbitmq"
  solr:
    image: solr:6.6
    container_name: solr
    volumes:
      # hydroshare repository
      - ".:/hydroshare"
      - "solr_data_vol:/opt/solr/server/solr"
    ports:
      - "8983"
    command: ["solr-foreground"]
  hydroshare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hydroshare
    hostname: hydroshare
    devices:
      - "/dev/fuse"
    privileged: true
    environment:
      POSTGIS_HOST: postgis
      POSTGIS_PORT: 5432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      RABBITMQ_PORT_5672_TCP_ADDR: rabbitmq
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      TMP: /hs_tmp
      POSTGIS_PORT_5432_TCP_ADDR: postgis
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
    volumes:
      # hydroshare repository
      - ".:/hydroshare"
      # shared location for gunicorn.sock between containers
      - "temp_vol:/hs_tmp"
      # temp directory shared with celery workers
      - "share_vol:/shared_tmp"
    ports:
      - "1338:2022"
      - "8000:8000"
    links:
      - postgis:postgis
      - solr:solr
      - rabbitmq:rabbitmq
      - data.local.org:data.local.org
    depends_on:
      - postgis
      - solr
      - rabbitmq
      - data.local.org
    stdin_open: true
    tty: true
    command: /bin/bash init-hydroshare
  defaultworker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: defaultworker
    hostname: defaultworker
    environment:
      POSTGIS_HOST: postgis
      POSTGIS_PORT: 5432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      PGPASSWORD: postgres
      C_FORCE_ROOT: 1
      RABBITMQ_PORT_5672_TCP_ADDR: rabbitmq
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      POSTGIS_PORT_5432_TCP_ADDR: postgis
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
      COLUMNS: 80
    ports:
      - "5555:5555"
    volumes:
      - ".:/hydroshare"
    links:
      - postgis:postgis
      - rabbitmq:rabbitmq
      - data.local.org:data.local.org
    depends_on:
      - hydroshare
      - postgis
      - solr
      - rabbitmq
      - data.local.org
    stdin_open: true
    tty: true
    command: /bin/bash init-defaultworker
volumes:
  idata_iconf_vol:
  idata_vault_vol:
  idata_pgres_vol:
  idata_home_vol:
  iuser_iconf_vol:
  iuser_vault_vol:
  iuser_pgres_vol:
  iuser_home_vol:
  postgis_data_vol:
  solr_data_vol:
  temp_vol:
  share_vol:
  rabbitmq_data_vol:
