#!/bin/bash

# TODO - deprecate from workflow now that the entire volume is shared (~/hydroshare)

mkdir /tmp/media
pushd $PWD > /dev/null
cp "$1" /tmp
cd /tmp
tar -xzf "$1" 
cd media
scp -r -P 1338 . root@localhost:/home/docker/hydroshare/hydroshare/static
popd
rm -rf /tmp/media

