#!/usr/bin/env bash

PYTHON_MODULES="$(find hs_* -not -path '*migration*' -name '*.py' )"
#pylint $PYTHON_MODULES --output-format=html > pylint-results.html
pylint -f parseable $PYTHON_MODULES | tee pylint.out

exit 0;