# Generated by Django 3.2.15 on 2023-02-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
            ],
            options={
                'verbose_name': 'External Resource',
                'ordering': ('_order',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hs_core.baseresource',),
        ),
    ]
