# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-03 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_modelinstance', '0006_auto_20151216_1511'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='executedby',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='executedby',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='executedby',
            name='model_program_fk',
        ),
        migrations.RemoveField(
            model_name='modelinstancemetadata',
            name='coremetadata_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='modeloutput',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modeloutput',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ModelInstanceResource',
        ),
        migrations.DeleteModel(
            name='ExecutedBy',
        ),
        migrations.DeleteModel(
            name='ModelInstanceMetaData',
        ),
        migrations.DeleteModel(
            name='ModelOutput',
        ),
    ]
