HS_PATH=/home/hydro/hydroshare
HOST_SSL_DIR=/opt/hs-certs
HS_DATABASE=pg.deploy.sql
HS_LOG_FILES=/var/hydroshare/log
HS_SERVICE_UID=20028
HS_SERVICE_GID=10000
USE_NGINX=true
USE_SSL=true
USE_SECURITY=false
USE_HTTP_AUTH=false
FQDN_OR_IP=www-hydroshare.edc.renci.org
NGINX_DIR=/home/hydro/hydroshare/nginx
SOLR_VM=db1-beta-hydroshare.edc.renci.org
POSTGRES_VM=db1-beta-hydroshare.edc.renci.org
SSL_CERT_DIR=/opt/hs-certs
SSL_CERT_FILE=SSL.crt
SSL_KEY_FILE=server.key
IRODS_LOCAL_MOUNT=/irods
IRODS_DOCKER_MAP=/irods
IRODS_DATA_ROOT=/irods/hydroshare/vaults/hydrotest/home/betaDataProxy/
# IRODS_USER_ROOT=/irods/hydroshare/vaults/usersdev/home/betaUserProxy/
# IRODS_CACHE_ROOT=/irods/hydroshare_vault/nginx_tmp/beta/cache/
# Location of the private key on the host vm (not the hydroshare container)
PRIVATE_KEY_FILE_FOR_HS_USER_ZONE='/opt/.ssh/id_ed25519_hs'
SENDFILE_IRODS_USER=irods
SENDFILE_IRODS_GROUP=irods
SENDFILE_IRODS_USER_ID=20022
SENDFILE_IRODS_GROUP_ID=10000
IRODS_DATA_URI=irods-data
# IRODS_USER_URI=irods-user
# IRODS_CACHE_URI=irods-cache
CELERY_CONCURRENCY=4
