# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-12 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_core', '0047_auto_20200202_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPrefToPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(editable=False)),
                ('group_pref', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.GroupPreferences')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRecToPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='subject', editable=False, max_length=255)),
                ('value', models.CharField(default='value', editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LDAWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ODM2', 'ODM2'), ('CSDMS', 'CSDMS'), ('Customized', 'Customized')], max_length=10)),
                ('word_type', models.CharField(choices=[('go', 'go'), ('stop', 'stop')], max_length=4)),
                ('part', models.CharField(choices=[('name', 'name'), ('decor', 'decor')], max_length=5)),
                ('value', models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipPrefToPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_for', models.CharField(choices=[('Resource', 'Resource'), ('User', 'User'), ('Group', 'Group')], max_length=8)),
                ('weight', models.FloatField(editable=False)),
                ('state', models.CharField(choices=[('Seen', 'Seen'), ('Rejected', 'Rejected')], default='Seen', max_length=8)),
                ('own_pref', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.OwnershipPreferences')),
                ('pair', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.KeyValuePair')),
            ],
        ),
        migrations.CreateModel(
            name='PropensityPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PropensityPrefToPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_for', models.CharField(choices=[('Resource', 'Resource'), ('User', 'User'), ('Group', 'Group')], max_length=8)),
                ('weight', models.FloatField(editable=False)),
                ('state', models.CharField(choices=[('Seen', 'Seen'), ('Rejected', 'Rejected')], default='Seen', max_length=8)),
                ('pair', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.KeyValuePair')),
                ('prop_pref', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.PropensityPreferences')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField(default=0.0, editable=False)),
                ('state', models.IntegerField(choices=[(1, 'New'), (2, 'Shown'), (3, 'Explored'), (4, 'Approved'), (5, 'Dismissed')], default=1, editable=False)),
                ('candidate_group', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='group_recommendation', to='auth.Group')),
                ('keywords', models.ManyToManyField(editable=False, related_name='for_group_rec', through='hs_explore.GroupRecToPair', to='hs_explore.KeyValuePair')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField(default=0.0, editable=False)),
                ('rec_type', models.CharField(choices=[('Ownership', 'Ownership'), ('Propensity', 'Propensity'), ('Combination', 'Combination')], max_length=11, null=True)),
                ('state', models.IntegerField(choices=[(1, 'New'), (2, 'Shown'), (3, 'Explored'), (4, 'Approved'), (5, 'Dismissed')], default=1, editable=False)),
                ('candidate_resource', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='resource_recommendation', to='hs_core.BaseResource')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField(default=0.0, editable=False)),
                ('state', models.IntegerField(choices=[(1, 'New'), (2, 'Shown'), (3, 'Explored'), (4, 'Approved'), (5, 'Dismissed')], default=1, editable=False)),
                ('candidate_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interacted_resources', models.ManyToManyField(editable=False, related_name='interested_resources', to='hs_core.BaseResource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePrefToPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_type', models.CharField(choices=[('Ownership', 'Ownership'), ('Propensity', 'Propensity')], max_length=10, null=True)),
                ('weight', models.FloatField(editable=False)),
                ('state', models.CharField(choices=[('Seen', 'Seen'), ('Rejected', 'Rejected')], default='Seen', max_length=8)),
                ('pair', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.KeyValuePair')),
                ('res_pref', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.ResourcePreferences')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRecToPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(editable=False)),
                ('pair', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.KeyValuePair')),
                ('recommendation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.RecommendedResource')),
            ],
        ),
        migrations.CreateModel(
            name='UserInteractedResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interacted_resources', models.ManyToManyField(editable=False, related_name='interacted_resources', to='hs_core.BaseResource')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNeighbors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbors', models.ManyToManyField(editable=False, related_name='user_neighbors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbors', models.ManyToManyField(editable=False, related_name='nearest_neighbors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrefToPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_type', models.CharField(choices=[('Ownership', 'Ownership'), ('Propensity', 'Propensity')], max_length=10, null=True)),
                ('weight', models.FloatField(editable=False)),
                ('state', models.CharField(choices=[('Seen', 'Seen'), ('Rejected', 'Rejected')], default='Seen', max_length=8)),
                ('pair', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.KeyValuePair')),
                ('user_pref', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.UserPreferences')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecToPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(editable=False)),
                ('pair', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.KeyValuePair')),
                ('recommendation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.RecommendedUser')),
            ],
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferences',
            field=models.ManyToManyField(editable=False, related_name='for_user_pref', through='hs_explore.UserPrefToPair', to='hs_explore.KeyValuePair'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcepreferences',
            name='preferences',
            field=models.ManyToManyField(editable=False, related_name='for_res_pref', through='hs_explore.ResourcePrefToPair', to='hs_explore.KeyValuePair'),
        ),
        migrations.AddField(
            model_name='resourcepreferences',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendeduser',
            name='keywords',
            field=models.ManyToManyField(editable=False, related_name='for_user_rec', through='hs_explore.UserRecToPair', to='hs_explore.KeyValuePair'),
        ),
        migrations.AddField(
            model_name='recommendeduser',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendedresource',
            name='keywords',
            field=models.ManyToManyField(editable=False, related_name='for_resource_rec', through='hs_explore.ResourceRecToPair', to='hs_explore.KeyValuePair'),
        ),
        migrations.AddField(
            model_name='recommendedresource',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propensitypreferences',
            name='preferences',
            field=models.ManyToManyField(editable=False, related_name='for_prop_pref', through='hs_explore.PropensityPrefToPair', to='hs_explore.KeyValuePair'),
        ),
        migrations.AddField(
            model_name='propensitypreferences',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownershippreferences',
            name='preferences',
            field=models.ManyToManyField(editable=False, related_name='for_own_pref', through='hs_explore.OwnershipPrefToPair', to='hs_explore.KeyValuePair'),
        ),
        migrations.AddField(
            model_name='ownershippreferences',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='keyvaluepair',
            unique_together=set([('key', 'value')]),
        ),
        migrations.AddField(
            model_name='grouprectopair',
            name='pair',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.KeyValuePair'),
        ),
        migrations.AddField(
            model_name='grouprectopair',
            name='recommendation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.RecommendedGroup'),
        ),
        migrations.AddField(
            model_name='grouppreftopair',
            name='pair',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hs_explore.KeyValuePair'),
        ),
        migrations.AddField(
            model_name='grouppreferences',
            name='preferences',
            field=models.ManyToManyField(editable=False, related_name='for_group_pref', through='hs_explore.GroupPrefToPair', to='hs_explore.KeyValuePair'),
        ),
        migrations.AlterUniqueTogether(
            name='userrectopair',
            unique_together=set([('recommendation', 'pair')]),
        ),
        migrations.AlterUniqueTogether(
            name='userpreftopair',
            unique_together=set([('user_pref', 'pair', 'pref_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourcerectopair',
            unique_together=set([('recommendation', 'pair')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourcepreftopair',
            unique_together=set([('res_pref', 'pair', 'pref_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='recommendeduser',
            unique_together=set([('user', 'candidate_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='recommendedresource',
            unique_together=set([('user', 'candidate_resource', 'rec_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='recommendedgroup',
            unique_together=set([('user', 'candidate_group')]),
        ),
        migrations.AlterUniqueTogether(
            name='propensitypreftopair',
            unique_together=set([('prop_pref', 'pref_for', 'pair')]),
        ),
        migrations.AlterUniqueTogether(
            name='ownershippreftopair',
            unique_together=set([('own_pref', 'pref_for', 'pair')]),
        ),
        migrations.AlterUniqueTogether(
            name='grouprectopair',
            unique_together=set([('recommendation', 'pair')]),
        ),
        migrations.AlterUniqueTogether(
            name='grouppreftopair',
            unique_together=set([('group_pref', 'pair')]),
        ),
    ]
