# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-09 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorageCreds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('json', models.TextField()),
                ('user', models.ForeignKey(editable=False, help_text='user assigning a label', on_delete=django.db.models.deletion.CASCADE, related_name='creds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
