# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-09 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstoragecreds',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='userstoragecreds',
            name='servicecode',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Google'), (2, 'DropBox'), (3, 'Box')], default=0, editable=False),
        ),
        migrations.AddField(
            model_name='userstoragecreds',
            name='username',
            field=models.CharField(default='foo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstoragecreds',
            name='user',
            field=models.ForeignKey(editable=False, help_text='user for this credential information', on_delete=django.db.models.deletion.CASCADE, related_name='creds', to=settings.AUTH_USER_MODEL),
        ),
    ]
