# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-09 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_storage', '0002_auto_20210409_1943'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstoragecreds',
            unique_together=set([('user', 'nickname')]),
        ),
    ]
