# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-22 15:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hs_access_control", "0023_auto_20190131_1523"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupcommunityprivilege",
            name="allow_view",
        ),
    ]
