# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-18 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0023_auto_20190131_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaccess',
            name='unlisted',
            field=models.BooleanField(default=False, editable=False, help_text=b'whether group appears in group listings'),
        ),
    ]
