# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-14 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0023_auto_20190131_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupresourceprivilege',
            name='exhibit',
            field=models.BooleanField(default=True, editable=False, help_text=b'whether to exhibit this resource as a public product'),
        ),
    ]
