# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-10 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hs_access_control", "0026_auto_20200603_2110"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembershiprequest",
            name="redeemed",
            field=models.BooleanField(default=False),
        ),
    ]
