# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-13 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0027_groupmembershiprequest_redeemed'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='customization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
