# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0032_auto_20210607_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaccess',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groupaccess',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
