# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-17 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import hs_access_control.models.community
import hs_access_control.models.group


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0032_auto_20210607_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=hs_access_control.models.community.get_upload_path),
        ),
        migrations.AlterField(
            model_name='groupaccess',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=hs_access_control.models.group.get_upload_path),
        ),
    ]
