# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-11 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('hs_access_control', '0035_groupmembershiprequest_justification'), ('hs_access_control', '0036_groupaccess_requires_justification')]

    dependencies = [
        ('hs_access_control', '0034_resourceaccess_allow_private_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembershiprequest',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupaccess',
            name='requires_justification',
            field=models.BooleanField(default=False, editable=False, help_text='whether membership requests include justification'),
        ),
    ]
