# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0034_resourceaccess_allow_private_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembershiprequest',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
