# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-01 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0033_auto_20211118_1919'),
        ('hs_access_control', '0034_resourceaccess_allow_private_sharing'),
        ('hs_access_control', '0035_auto_20211025_1948'),
    ]

    operations = [
    ]
