# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-10 12:13
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields
import theme.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0035_auto_20220322_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=theme.utils.get_upload_path_community),
        ),
        migrations.AlterField(
            model_name='groupaccess',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=theme.utils.get_upload_path_group),
        ),
    ]
