# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-10 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0035_groupmembershiprequest_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaccess',
            name='requires_justification',
            field=models.BooleanField(default=False, editable=False, help_text='whether membership requests include justification'),
        ),
    ]
