# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-25 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0036_merge_20220325_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='closed',
        ),
    ]
