# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-01 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0036_merge_20220401_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='community'),
        ),
    ]
