# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-03 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0035_auto_20220322_1313'),
        ('hs_access_control', '0037_auto_20220401_2243'),
    ]

    operations = [
    ]
