# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-06 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0037_remove_community_closed'),
        ('hs_access_control', '0038_merge_20220403_1230'),
    ]

    operations = [
    ]
