# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-26 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0039_community_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
