# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-12 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0040_community_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
