# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-29 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0043_auto_20220520_2047'),
        ('hs_access_control', '0037_resourceaccess_review_pending'),
    ]

    operations = [
    ]
