# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-19 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_access_control', '0044_merge_20220729_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(editable=False, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('community_to_approve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2crequest', to='hs_access_control.Community')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u2crequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
