# Generated by Django 3.2.15 on 2023-03-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0045_auto_20221103_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcommunity',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
