# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-19 19:02
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields
import theme.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0045_requestcommunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banner',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=theme.utils.get_upload_path_community),
        ),
    ]
