# Generated by Django 4.2.17 on 2024-12-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0046_requestcommunity_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResourcePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('resource_id', models.CharField(max_length=32)),
                ('privilege', models.IntegerField(choices=[(1, 'Owner'), (2, 'Change'), (3, 'View')], default=4, editable=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userresourcepermission',
            constraint=models.UniqueConstraint(fields=('user_id', 'resource_id'), name='user_resource_permission_unique'),
        ),
    ]
