# Generated by Django 4.2.23 on 2025-12-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0046_requestcommunity_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='discoverable',
            field=models.BooleanField(db_index=True, default=False, help_text='whether resource is discoverable by everyone'),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='immutable',
            field=models.BooleanField(db_index=True, default=False, help_text='whether to prevent all changes to the resource'),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='public',
            field=models.BooleanField(db_index=True, default=False, help_text='whether resource data can be viewed by everyone'),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='published',
            field=models.BooleanField(db_index=True, default=False, help_text='whether resource has been published'),
        ),
    ]
