# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-23 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0046_community_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='requestcommunity',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
    ]
