# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-24 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0047_auto_20220823_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='requestcommunity',
            options={'ordering': ['date_requested']},
        ),
        migrations.RenameField(
            model_name='community',
            old_name='auto_approve',
            new_name='auto_approve_group',
        ),
        migrations.AddField(
            model_name='community',
            name='auto_approve_resource',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
