# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-25 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0048_auto_20220824_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityrequest',
            name='owner',
        ),
        migrations.AddField(
            model_name='requestcommunity',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CommunityRequest',
        ),
    ]
