# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0049_auto_20221025_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcommunity',
            name='approved',
        ),
        migrations.AddField(
            model_name='requestcommunity',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestcommunity',
            name='pending_approval',
            field=models.BooleanField(default=True),
        ),
    ]
