# Generated by Django 3.2.25 on 2024-08-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_s3', '0003_auto_20240809_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RodsEnvironment',
        ),
    ]
