# Generated by Django 3.2.25 on 2024-08-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_s3', '0004_delete_rodsenvironment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avu',
            name='attVal',
            field=models.TextField(null=True),
        ),
    ]
