# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-04 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_communities', '0003_auto_20190903_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='order',
        ),
    ]
