# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-13 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hs_core.hs_rdf


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hs_geographic_feature_resource', '0002_auto_20170612_2159'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='OriginalCoverageGeofeature',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('object_id', models.PositiveIntegerField()),
                        ('northlimit', models.FloatField()),
                        ('southlimit', models.FloatField()),
                        ('westlimit', models.FloatField()),
                        ('eastlimit', models.FloatField()),
                        ('projection_string', models.TextField(blank=True, null=True)),
                        ('projection_name', models.TextField(blank=True, max_length=256, null=True)),
                        ('datum', models.TextField(blank=True, max_length=256, null=True)),
                        ('unit', models.TextField(blank=True, max_length=256, null=True)),
                        ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_geographic_feature_resource_originalcoveragegeofeature_related', to='contenttypes.ContentType')),
                    ],
                    bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
                ),
                migrations.AlterUniqueTogether(
                    name='originalcoverage',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='originalcoverage',
                    name='content_type',
                ),
                migrations.DeleteModel(
                    name='OriginalCoverage',
                ),
                migrations.AlterUniqueTogether(
                    name='originalcoveragegeofeature',
                    unique_together=set([('content_type', 'object_id')]),
                ),
            ],
            database_operations=[
                migrations.RenameModel("OriginalCoverage", "OriginalCoverageGeofeature")
            ]
        )
    ]
