# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_geographic_feature_resource', '0002_auto_20170612_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeographicFeatureResource',
        ),
    ]
