# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-13 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_geographic_feature_resource', '0003_auto_20220413_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographicfeaturemetadata',
            name='coremetadata_ptr',
        ),
        migrations.DeleteModel(
            name='GeographicFeatureResource',
        ),
        migrations.DeleteModel(
            name='GeographicFeatureMetaData',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='geometryinformation',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='geometryinformation',
                    name='content_type',
                ),
                migrations.AlterUniqueTogether(
                    name='originalcoveragegeofeature',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='originalcoveragegeofeature',
                    name='content_type',
                ),
                migrations.RemoveField(
                    model_name='fieldinformation',
                    name='content_type',
                ),
                migrations.DeleteModel(
                    name='FieldInformation',
                ),
                migrations.DeleteModel(
                    name='GeometryInformation',
                ),
                migrations.DeleteModel(
                    name='OriginalCoverageGeofeature',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='FieldInformation',
                    table='hs_file_types_fieldinformation',
                ),
                migrations.AlterModelTable(
                    name='GeometryInformation',
                    table='hs_file_types_geometryinformation',
                ),
                migrations.AlterModelTable(
                    name='OriginalCoverageGeofeature',
                    table='hs_file_types_originalcoveragegeofeature',
                ),
            ]
        )
    ]
