# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-17 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_core', '0060_auto_20220202_1732'),
        ('hs_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(editable=False, null=True)),
                ('tempfile', models.TextField(editable=False, null=True)),
                ('size', models.IntegerField(editable=False, null=True)),
                ('uploaded', models.IntegerField(editable=False, null=True)),
                ('resource', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_core.BaseResource')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Uploads',
        ),
        migrations.AlterUniqueTogether(
            name='upload',
            unique_together=set([('resource', 'path')]),
        ),
    ]
