# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-11 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0060_auto_20220311_1212'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='filename',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uploads',
            name='path',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uploads',
            name='resource',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_core.BaseResource'),
        ),
        migrations.AddField(
            model_name='uploads',
            name='size',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uploads',
            name='tempfile',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uploads',
            name='uploaded',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uploads',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='bytes_uploaded',
        ),
        migrations.AlterUniqueTogether(
            name='uploads',
            unique_together=set([('resource', 'path', 'filename')]),
        ),
    ]
