# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-07 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_upload', '0002_auto_20220317_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='uploaded',
        ),
    ]
