# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-11 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_upload', '0002_auto_20220311_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploads',
            new_name='Upload',
        ),
    ]
