# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0039_doi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresource',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseresource',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
