# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-21 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0042_auto_20190402_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
