# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-02 18:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hs_core", "0044_auto_20190701_2207"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Topics",
        ),
    ]
