# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-04 20:35


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hs_core", "0045_delete_topics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bags",
            name="content_type",
        ),
        migrations.DeleteModel(
            name="Bags",
        ),
    ]
