# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-01 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0045_delete_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseresource',
            name='last_changed_by',
            field=models.ForeignKey(default=User.objects.get(username='admin').id, help_text=b'The person who last changed the resource', on_delete=django.db.models.deletion.CASCADE, related_name='last_changed_hs_core_baseresource', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
