# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-11 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0046_auto_20191001_2235'),
        ('hs_core', '0046_auto_20191104_2035'),
    ]

    operations = [
    ]
