# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-04 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0046_auto_20191104_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresource',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
