# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-12 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0047_auto_20200507_0037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericResource',
        ),
    ]
