# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-15 13:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0050_auto_20200611_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresource',
            name='computed_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
    ]
