# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-20 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0050_auto_20200611_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoAVU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='baseresource',
            name='storage_type',
            field=models.IntegerField(choices=[(1, 'iRODs'), (2, 'Federated iRODs'), (3, 'Linux')], default=1, editable=False),
        ),
    ]
