# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-17 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0052_tasknotification_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknotification',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
