# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-26 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0052_tasknotification_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknotification',
            name='status',
            field=models.CharField(choices=[('progress', 'Progress'), ('failed', 'Failed'), ('aborted', 'Aborted'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
