# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0047_auto_20200507_0037'),
        ('hs_core', '0057_auto_20210104_2106'),
    ]

    operations = [
    ]
