# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-01 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django_irods.storage
import hs_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0060_auto_20220202_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='resource_file',
            field=models.FileField(default=None, max_length=4096, null=True, storage=django_irods.storage.IrodsStorage(), upload_to=hs_core.models.get_path),
        ),
        migrations.AlterIndexTogether(
            name='resourcefile',
            index_together=set([('object_id', 'resource_file')]),
        ),
    ]
