# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-11 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import hs_core.models
import hs_linux.storage


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0060_auto_20220202_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='linux_resource_file',
            field=models.FileField(blank=True, max_length=4096, null=True, storage=hs_linux.storage.LinuxStorage(), upload_to=hs_core.models.get_path),
        ),
    ]
