# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django_irods.storage
import hs_core.models
import hs_linux.storage


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0061_resourcefile_linux_resource_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcefile',
            old_name='fed_resource_file',
            new_name='_fed_resource_file',
        ),
        migrations.RenameField(
            model_name='resourcefile',
            old_name='linux_resource_file',
            new_name='_linux_resource_file',
        ),
        migrations.RenameField(
            model_name='resourcefile',
            old_name='resource_file',
            new_name='_resource_file',
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='_fed_resource_file',
            field=models.FileField(default=None, max_length=4096, null=True, storage=hs_core.models.FedStorage(), upload_to=hs_core.models.get_path),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='_linux_resource_file',
            field=models.FileField(default=None, max_length=4096, null=True, storage=hs_linux.storage.LinuxStorage(), upload_to=hs_core.models.get_path),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='_resource_file',
            field=models.FileField(default=None, max_length=4096, null=True, storage=django_irods.storage.IrodsStorage(), upload_to=hs_core.models.get_path),
        ),
        migrations.AlterIndexTogether(
            name='resourcefile',
            index_together=set([('object_id', '_fed_resource_file'), ('object_id', '_resource_file'), ('object_id', '_linux_resource_file')]),
        ),
    ]
