# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0061_auto_20220404_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='statement',
            field=models.TextField(),
        ),
    ]
