# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models

from hs_core.hydroshare import set_dirty_bag_flag
from hs_core.models import BaseResource


def fix_missing_license_statement(apps, schema_editor):
    for res in BaseResource.objects.all().iterator():
        res = res.get_content_model()
        if res.metadata is None:
            continue
        rights = res.metadata.rights
        if len(rights.statement.strip()) == 0:
            rights.statement = rights.url
            rights.save()
            set_dirty_bag_flag(res)


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0061_auto_20220404_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='statement',
            field=models.TextField(),
        ),
        migrations.RunPython(fix_missing_license_statement),
    ]
