# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-24 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0061_resourcefile_linux_resource_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcefile',
            old_name='fed_resource_file',
            new_name='_fed_resource_file',
        ),
        migrations.RenameField(
            model_name='resourcefile',
            old_name='linux_resource_file',
            new_name='_linux_resource_file',
        ),
        migrations.RenameField(
            model_name='resourcefile',
            old_name='resource_file',
            new_name='_resource_file',
        ),
        migrations.AlterIndexTogether(
            name='resourcefile',
            index_together=set([('object_id', '_fed_resource_file'), ('object_id', '_linux_resource_file'), ('object_id', '_resource_file')]),
        ),
    ]
