# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-01 20:14
from __future__ import unicode_literals

from django.db import migrations


def remove_pending_citations_from_relations(apps, schema_editor):
    Relation = apps.get_model("hs_core", "Relation")
    for relation in Relation.objects.all():
        if relation.value:
            sep = ', DOI for this published resource is pending activation'
            head, _, _ = relation.value.partition(sep)
            relation.value = head
            relation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0062_auto_20220520_1449'),
    ]

    operations = [
        migrations.RunPython(remove_pending_citations_from_relations),
    ]
