# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-24 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0062_auto_20220224_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresource',
            name='storage_type',
            field=models.IntegerField(choices=[(1, 'iRODs'), (2, 'Federated iRODs'), (3, 'Linux')], default=1, editable=False),
        ),
    ]
