# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-24 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django_irods.storage
import hs_core.models
import hs_linux.storage


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0063_baseresource_storage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='_fed_resource_file',
            field=models.FileField(default=None, max_length=4096, null=True, storage=hs_core.models.FedStorage(), upload_to=hs_core.models.get_path),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='_linux_resource_file',
            field=models.FileField(default=None, max_length=4096, null=True, storage=hs_linux.storage.LinuxStorage(), upload_to=hs_core.models.get_path),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='_resource_file',
            field=models.FileField(default=None, max_length=4096, null=True, storage=django_irods.storage.IrodsStorage(), upload_to=hs_core.models.get_path),
        ),
    ]
