# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-14 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0065_auto_20221004_1707'),
        ('hs_core', '0065_auto_20221004_2012'),
    ]

    operations = [
    ]
