# Generated by Django 3.2.15 on 2022-11-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0065_auto_20220922_1352'),
        ('hs_core', '0066_merge_20221014_1428'),
    ]

    operations = [
    ]
