# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hs_core.hs_rdf


def migrate_relations_to_geoconnex(apps, schema_editor):
    Relation = apps.get_model("hs_core", "Relation")
    BaseResource = apps.get_model("hs_core", "BaseResource")
    for relation in Relation.objects.filter(type="relation"):
        res = BaseResource.objects.get(object_id=relation.object_id)
        if "geoconnex" in relation.value:
            print(f"Creating new geoconnex relation for res_id:{res.short_id}, value:{relation.value}")
            res.metadata.create_element('geospatialrelation',
                                        type='relation',
                                        value=relation.value)
            relation.delete()
        else:
            print(f"Encountered resource with non geoconnex generic 'relation' type. Res_id:{res.short_id}")


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hs_core', '0066_merge_20221014_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeospatialRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('relation', 'The content of this resource is related to')], max_length=100)),
                ('value', models.TextField()),
                ('text', models.TextField(max_length=100)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_core_geospatialrelation_related', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
        ),
        migrations.RunPython(migrate_relations_to_geoconnex),
        migrations.AlterField(
            model_name='relation',
            name='type',
            field=models.CharField(choices=[('isPartOf', 'The content of this resource is part of'), ('hasPart', 'This resource includes'), ('isExecutedBy', 'The content of this resource can be executed by'), ('isCreatedBy', 'The content of this resource was created by a related App or software program'), ('isVersionOf', 'This resource updates and replaces a previous version'), ('isReplacedBy', 'This resource has been replaced by a newer version'), ('isDescribedBy', 'This resource is described by'), ('conformsTo', 'This resource conforms to established standard described by'), ('hasFormat', 'This resource has a related resource in another format'), ('isFormatOf', 'This resource is a different format of'), ('isRequiredBy', 'This resource is required by'), ('requires', 'This resource requires'), ('isReferencedBy', 'This resource is referenced by'), ('references', 'The content of this resource references'), ('replaces', 'This resource replaces'), ('source', 'The content of this resource is derived from'), ('isSimilarTo', 'The content of this resource is similar to')], max_length=100),
        ),
    ]
