# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-07 15:13
from __future__ import unicode_literals

from django.db import migrations
from hs_core.models import Relation, BaseResource, GeospatialRelation


def migrate_relations_to_geoconnex(apps, schema_editor):
    for relation in Relation.objects.filter(type="relation"):
        res = BaseResource.objects.get(object_id=relation.object_id)
        if "geoconnex" in relation.value:
            print(f"\nAttempting to create new geoconnex relation for res_id:{res.short_id}, value:{relation.value}")
            try:
                res.metadata.create_element('geospatialrelation',
                                            type='relation',
                                            value=relation.value)
            except AttributeError as ex:
                print(f"Metadata object missing for res_id:{res.short_id}, value:{relation.value}. Skipping.")
                print(ex)
                continue
            relation.delete()
        else:
            print(f"Encountered resource with non geoconnex generic 'relation' type. Res_id:{res.short_id}")


def get_geoconnex_text(apps, schema_editor):
    GeospatialRelation.sync_all_text()


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0067_auto_20221107_1513'),
    ]

    operations = [
        migrations.RunPython(migrate_relations_to_geoconnex),
        migrations.RunPython(get_geoconnex_text)
    ]
