# Generated by Django 3.2.15 on 2022-12-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0067_auto_20221107_1513'),
        ('hs_core', '0068_alter_date_type'),
    ]

    operations = [
    ]
