# Generated by Django 3.2.15 on 2023-04-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0069_merge_0067_auto_20221107_1513_0068_alter_date_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericResource',
        ),
    ]
