# Generated by Django 3.2.15 on 2023-04-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0069_merge_0067_auto_20221107_1513_0068_alter_date_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericResource',
        ),
        migrations.AlterField(
            model_name='date',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('valid', 'Valid'), ('available', 'Available'), ('reviewStarted', 'Review Started'), ('published', 'Published')], max_length=20),
        ),
    ]
