# Generated by Django 3.2.15 on 2023-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0070_delete_genericresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('valid', 'Valid'), ('available', 'Available'), ('reviewStarted', 'Review Started'), ('published', 'Published')], max_length=20),
        ),
    ]
