# Generated by Django 3.2.19 on 2023-07-27 18:50

from django.db import migrations, models
import django_irods.storage
import hs_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0071_alter_date_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='fed_resource_file',
            field=models.FileField(blank=True, max_length=4096, null=True, storage=hs_core.models.FedStorage(), unique=True, upload_to=hs_core.models.get_path),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='resource_file',
            field=models.FileField(blank=True, max_length=4096, null=True, storage=django_irods.storage.IrodsStorage(), unique=True, upload_to=hs_core.models.get_path),
        ),
    ]
