# Generated by Django 3.2.19 on 2023-08-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0072_baseresource_repaired'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresource',
            name='files_checked',
            field=models.DateTimeField(null=True),
        ),
    ]
