# Generated by Django 3.2.15 on 2023-08-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0073_resource_file_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='_checksum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='_modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
