# Generated by Django 3.2.19 on 2023-07-27 18:50

import logging
from django.db import migrations
from hs_core.management.utils import fix_resourcefile_duplicates


def migrate_resourcefiles(apps, schema_editor):
    logger = logging.getLogger(__name__)
    fix_resourcefile_duplicates(dry_run=False, logger=logger, get_model=True)


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0074_auto_20230905_1959'),
    ]

    operations = [
        migrations.RunPython(migrate_resourcefiles),
    ]
