# Generated by Django 3.2.20 on 2024-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0077_baseresource_spam_allowlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('valid', 'Valid'), ('available', 'Available'), ('reviewStarted', 'Review Started'), ('published', 'Published'), ('bag_last_downloaded', 'Bag Last Downloaded')], max_length=20),
        ),
    ]
