# Generated by Django 3.2.20 on 2024-02-07 17:01

from django.db import migrations, models
import hs_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0077_baseresource_spam_allowlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='abstract',
            field=models.TextField(validators=[hs_core.models.validate_abstract]),
        ),
    ]
