# Generated by Django 3.2.20 on 2024-02-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0078_alter_date_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresource',
            name='bag_last_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('valid', 'Valid'), ('available', 'Available'), ('reviewStarted', 'Review Started'), ('published', 'Published')], max_length=20),
        ),
    ]
