# Generated by Django 3.2.20 on 2024-02-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0078_alter_description_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresource',
            name='bag_last_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
