# Generated by Django 3.2.25 on 2024-05-13 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('hs_core', '0080_baseresource_quota_holder'), ('hs_core', '0081_alter_baseresource_quota_holder'), ('hs_core', '0080_resourcefile_filesize_cache_updated'), ('hs_core', '0082_merge_20240509_1646')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_core', '0079_baseresource_bag_last_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresource',
            name='quota_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_holder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='filesize_cache_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
