# Generated by Django 3.2.25 on 2024-04-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0079_baseresource_bag_last_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='filesize_cache_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
