# Generated by Django 3.2.25 on 2024-04-13 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_core', '0079_baseresource_bag_last_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresource',
            name='quota_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_holder', to=settings.AUTH_USER_MODEL),
        ),
    ]
