# Generated by Django 3.2.25 on 2024-05-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0080_resourcefile_filesize_cache_updated'),
        ('hs_core', '0081_alter_baseresource_quota_holder'),
    ]

    operations = [
    ]
