# Generated by Django 3.2.25 on 2024-07-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0082_merge_20240509_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseresource',
            name='resource_federation_path',
        ),
        migrations.AlterIndexTogether(
            name='resourcefile',
            index_together={('object_id', 'resource_file')},
        ),
        migrations.RemoveField(
            model_name='resourcefile',
            name='fed_resource_file',
        ),
    ]
