# Generated by Django 3.2.25 on 2024-10-22 16:02

from django.db import migrations
from ..models import FundingAgency


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0084_remove_federation_from_db'),
    ]

    operations = [
        migrations.RunPython(FundingAgency.migrate_from_crossref_ror)
    ]
