# Generated by Django 4.2.16 on 2024-09-05 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_core', '0084_remove_federation_from_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseresource',
            name='creator',
            field=models.ForeignKey(help_text='This is the person who first uploaded the resource', on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='baseresource',
            name='last_changed_by',
            field=models.ForeignKey(default=1, help_text='The person who last changed the resource', on_delete=django.db.models.deletion.CASCADE, related_name='last_changed_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='baseresource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='date',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='description',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='format',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='fundingagency',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='geospatialrelation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='language',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='rights',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='title',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='type',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
    ]
