# Generated by Django 4.2.20 on 2025-05-24 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_core', '0085_alter_baseresource_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresource',
            name='denormalized_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='UserResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[(1, 'Owner'), (2, 'Change'), (3, 'View')], default=3)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_discovered', models.BooleanField(default=False)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_users', to='hs_core.baseresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'permission'], name='hs_core_use_user_id_135759_idx'), models.Index(fields=['user', 'is_favorite'], name='hs_core_use_user_id_cfed75_idx'), models.Index(fields=['user', 'is_discovered'], name='hs_core_use_user_id_b8a1d7_idx')],
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
