# Generated by Django 4.2.23 on 2025-09-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0085_alter_baseresource_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresource',
            name='cached_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
