# Generated by Django 4.2.23 on 2025-12-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0087_populate_resource_cached_metadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resourcefile',
            new_name='hs_core_res_object__5578ab_idx',
            old_fields=('object_id', 'resource_file'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='file_folder',
            field=models.CharField(db_index=True, default='', max_length=4096),
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_cit_content_648a76_idx'),
        ),
        migrations.AddIndex(
            model_name='contributor',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_con_content_8bf3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='coverage',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_cov_content_93bb24_idx'),
        ),
        migrations.AddIndex(
            model_name='creator',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_cre_content_5a77c7_idx'),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_dat_content_8fd882_idx'),
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_des_content_db5993_idx'),
        ),
        migrations.AddIndex(
            model_name='format',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_for_content_ebb845_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingagency',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_fun_content_9a1daf_idx'),
        ),
        migrations.AddIndex(
            model_name='geospatialrelation',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_geo_content_7ab41b_idx'),
        ),
        migrations.AddIndex(
            model_name='identifier',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_ide_content_ba5f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_lan_content_74229e_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_pub_content_d237e3_idx'),
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_rel_content_b3e2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcefile',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_res_content_0a5b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcefile',
            index=models.Index(fields=['logical_file_content_type', 'logical_file_object_id'], name='hs_core_res_logical_74800a_idx'),
        ),
        migrations.AddIndex(
            model_name='rights',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_rig_content_432b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_sub_content_3027bf_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_tit_content_07c374_idx'),
        ),
        migrations.AddIndex(
            model_name='type',
            index=models.Index(fields=['content_type', 'object_id'], name='hs_core_typ_content_612af4_idx'),
        ),
    ]
