# Generated by Django 4.2.23 on 2026-02-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0088_re_populate_resource_cached_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('job_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('job_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('requested_by', models.CharField(blank=True, max_length=150)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('retrying', 'Retrying'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('result_ref', models.CharField(blank=True, max_length=1000, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hs_core.baseresource')),
            ],
            options={
                'db_table': 'hs_core_jobstatus',
            },
        ),
    ]
