# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-11 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_labels', '0005_auto_20171127_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresourcelabels',
            name='label',
            field=models.TextField(max_length=75),
        ),
    ]
