# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_modflow_modelinstance', '0003_auto_20170501_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalelements',
            name='subsidencePackage',
            field=models.CharField(blank=True, choices=[('IBS', 'IBS'), ('SUB', 'SUB'), ('SWT', 'SWT')], max_length=100, null=True, verbose_name='Subsidence package'),
        ),
        migrations.AlterField(
            model_name='modelcalibration',
            name='observationProcessPackage',
            field=models.CharField(blank=True, choices=[('ADV2', 'ADV2'), ('CHOB', 'CHOB'), ('DROB', 'DROB'), ('DTOB', 'DTOB'), ('GBOB', 'GBOB'), ('HOB', 'HOB'), ('OBS', 'OBS'), ('RVOB', 'RVOB'), ('STOB', 'STOB')], max_length=100, null=True, verbose_name='Observation process package'),
        ),
    ]
