# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_modflow_modelinstance', '0004_auto_20200507_0037'),
        ('hs_modflow_modelinstance', '0004_auto_20200603_2110'),
    ]

    operations = [
    ]
