# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 02:55


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hs_file_types", "set_aggregation_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesetlogicalfile",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hs_composite_resource.CompositeResource",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="genericlogicalfile",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hs_composite_resource.CompositeResource",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="geofeaturelogicalfile",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hs_composite_resource.CompositeResource",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="georasterlogicalfile",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hs_composite_resource.CompositeResource",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="netcdflogicalfile",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hs_composite_resource.CompositeResource",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reftimeserieslogicalfile",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hs_composite_resource.CompositeResource",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="timeserieslogicalfile",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hs_composite_resource.CompositeResource",
            ),
            preserve_default=False,
        ),
    ]
