# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_file_types', '0012_auto_20220228_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='netcdffilemetadata',
            name='is_update_file',
            field=models.BooleanField(default=False),
        ),
    ]
