# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_file_types', '0013_netcdffilemetadata_is_update_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriesfilemetadata',
            name='is_update_file',
            field=models.BooleanField(default=False),
        ),
    ]
