# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-06 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hs_core.hs_rdf


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hs_file_types', '0014_timeseriesfilemetadata_is_update_file'),
    ]

    operations = [
            migrations.CreateModel(
                name='BandInformation',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('object_id', models.PositiveIntegerField()),
                    ('name', models.CharField(max_length=500, null=True)),
                    ('variableName', models.TextField(max_length=100, null=True)),
                    ('variableUnit', models.CharField(max_length=50, null=True)),
                    ('method', models.TextField(blank=True, null=True)),
                    ('comment', models.TextField(blank=True, null=True)),
                    ('noDataValue', models.TextField(blank=True, null=True)),
                    ('maximumValue', models.TextField(blank=True, null=True)),
                    ('minimumValue', models.TextField(blank=True, null=True)),
                    ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_file_types_bandinformation_related', to='contenttypes.ContentType')),
                ],
                options={
                    'abstract': False,
                },
                bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
            ),
            migrations.CreateModel(
                name='CellInformation',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('object_id', models.PositiveIntegerField()),
                    ('name', models.CharField(max_length=500, null=True)),
                    ('rows', models.IntegerField(null=True)),
                    ('columns', models.IntegerField(null=True)),
                    ('cellSizeXValue', models.FloatField(null=True)),
                    ('cellSizeYValue', models.FloatField(null=True)),
                    ('cellDataType', models.CharField(max_length=50, null=True)),
                    ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_file_types_cellinformation_related', to='contenttypes.ContentType')),
                ],
                bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
            ),
            migrations.CreateModel(
                name='OriginalCoverageRaster',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('object_id', models.PositiveIntegerField()),
                    ('_value', models.CharField(max_length=10000, null=True)),
                    ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_file_types_originalcoverageraster_related', to='contenttypes.ContentType')),
                ],
                bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
            ),
            migrations.AlterUniqueTogether(
                name='originalcoverageraster',
                unique_together=set([('content_type', 'object_id')]),
            ),
            migrations.AlterUniqueTogether(
                name='cellinformation',
                unique_together=set([('content_type', 'object_id')]),
            ),
        ]

