# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-02 21:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion

import hs_core.hs_rdf


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hs_file_types', '0016_auto_20220413_1959'),
    ]

    operations = [
            migrations.CreateModel(
                name='Method',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('object_id', models.PositiveIntegerField()),
                    ('series_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=[], size=None)),
                    ('is_dirty', models.BooleanField(default=False)),
                    ('method_code', models.CharField(max_length=50)),
                    ('method_name', models.CharField(max_length=200)),
                    ('method_type', models.CharField(max_length=200)),
                    ('method_description', models.TextField(blank=True, null=True)),
                    ('method_link', models.URLField(blank=True, null=True)),
                    ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_file_types_method_related', to='contenttypes.ContentType')),
                ],
                options={
                    'abstract': False,
                },
                bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
            ),
            migrations.CreateModel(
                name='ProcessingLevel',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('object_id', models.PositiveIntegerField()),
                    ('series_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=[], size=None)),
                    ('is_dirty', models.BooleanField(default=False)),
                    ('processing_level_code', models.CharField(max_length=50)),
                    ('definition', models.CharField(blank=True, max_length=200, null=True)),
                    ('explanation', models.TextField(blank=True, null=True)),
                    ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_file_types_processinglevel_related', to='contenttypes.ContentType')),
                ],
                options={
                    'abstract': False,
                },
                bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
            ),
            migrations.CreateModel(
                name='Site',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('object_id', models.PositiveIntegerField()),
                    ('series_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=[], size=None)),
                    ('is_dirty', models.BooleanField(default=False)),
                    ('site_code', models.CharField(max_length=200)),
                    ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                    ('elevation_m', models.FloatField(blank=True, null=True)),
                    ('elevation_datum', models.CharField(blank=True, max_length=50, null=True)),
                    ('site_type', models.CharField(blank=True, max_length=100, null=True)),
                    ('latitude', models.FloatField(blank=True, null=True)),
                    ('longitude', models.FloatField(blank=True, null=True)),
                    ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_file_types_site_related', to='contenttypes.ContentType')),
                ],
                options={
                    'abstract': False,
                },
                bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
            ),
            migrations.CreateModel(
                name='TimeSeriesResult',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('object_id', models.PositiveIntegerField()),
                    ('series_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=[], size=None)),
                    ('is_dirty', models.BooleanField(default=False)),
                    ('units_type', models.CharField(max_length=255)),
                    ('units_name', models.CharField(max_length=255)),
                    ('units_abbreviation', models.CharField(max_length=20)),
                    ('status', models.CharField(blank=True, max_length=255, null=True)),
                    ('sample_medium', models.CharField(max_length=255)),
                    ('value_count', models.IntegerField()),
                    ('aggregation_statistics', models.CharField(max_length=255)),
                    ('series_label', models.CharField(blank=True, max_length=255, null=True)),
                    ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_file_types_timeseriesresult_related', to='contenttypes.ContentType')),
                ],
                options={
                    'abstract': False,
                },
                bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
            ),
            migrations.CreateModel(
                name='UTCOffSet',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('object_id', models.PositiveIntegerField()),
                    ('series_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=[], size=None)),
                    ('is_dirty', models.BooleanField(default=False)),
                    ('value', models.FloatField(default=0.0)),
                    ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_file_types_utcoffset_related', to='contenttypes.ContentType')),
                ],
                options={
                    'abstract': False,
                },
                bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
            ),
            migrations.CreateModel(
                name='VariableTimeseries',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('object_id', models.PositiveIntegerField()),
                    ('series_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=[], size=None)),
                    ('is_dirty', models.BooleanField(default=False)),
                    ('variable_code', models.CharField(max_length=50)),
                    ('variable_name', models.CharField(max_length=100)),
                    ('variable_type', models.CharField(max_length=100)),
                    ('no_data_value', models.IntegerField()),
                    ('variable_definition', models.CharField(blank=True, max_length=255, null=True)),
                    ('speciation', models.CharField(blank=True, max_length=255, null=True)),
                    ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_file_types_variabletimeseries_related', to='contenttypes.ContentType')),
                ],
                options={
                    'abstract': False,
                },
                bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
            ),
        ]

