# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-13 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_file_types', '0017_timeseries_metadata_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelinstancelogicalfile',
            name='model_instance_type',
        ),
        migrations.RemoveField(
            model_name='modelprogramlogicalfile',
            name='model_program_type',
        ),
    ]
