# Generated by Django 3.2.15 on 2022-09-22 13:56

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_file_types', '0018_auto_20220713_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesetlogicalfile',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='filesetmetadata',
            name='extra_metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='filesetmetadata',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='genericfilemetadata',
            name='extra_metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='genericfilemetadata',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='genericlogicalfile',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='geofeaturefilemetadata',
            name='extra_metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='geofeaturefilemetadata',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='geofeaturelogicalfile',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='georasterfilemetadata',
            name='extra_metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='georasterfilemetadata',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='georasterlogicalfile',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='method',
            name='series_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='modelinstancefilemetadata',
            name='extra_metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='modelinstancefilemetadata',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='modelinstancefilemetadata',
            name='metadata_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='modelinstancelogicalfile',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='modelinstancelogicalfile',
            name='metadata_schema_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='modelprogramfilemetadata',
            name='extra_metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='modelprogramfilemetadata',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='modelprogramlogicalfile',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='modelprogramlogicalfile',
            name='metadata_schema_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='netcdffilemetadata',
            name='extra_metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='netcdffilemetadata',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='netcdflogicalfile',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='processinglevel',
            name='series_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='reftimeseriesfilemetadata',
            name='extra_metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='reftimeseriesfilemetadata',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='reftimeserieslogicalfile',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='site',
            name='series_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='timeseriesfilemetadata',
            name='extra_metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='timeseriesfilemetadata',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='timeseriesfilemetadata',
            name='value_counts',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='timeserieslogicalfile',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='timeseriesresult',
            name='series_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='utcoffset',
            name='series_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='variabletimeseries',
            name='series_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=list, size=None),
        ),
    ]
