__author__ = 'jeffersonheard'
from test_add_resource_files import *
from test_bagit import *
from test_comment_on_resource import *
from test_core_metadata import *
from test_create_account import *
from test_create_resource import *
from test_delete_resource_file import *
from test_delete_resource import *
from test_endorse_comment import *
from test_endorse_resource import *
from test_get_capabilities import *
from test_get_checksum import *
from test_get_comments import *
from test_get_endorsement import *
from test_get_resource_by_shortkey import *
from test_get_resource_file import *
from test_get_resource import *
from test_get_resource_types import *
from test_get_revisions import *
from test_group_from_id import *
from test_list_group_members import *
from test_publish_resource import *
from test_resolve_doi import *
from test_set_access_rules import *
from test_set_group_owner import *
from test_set_resource_owner import *
from test_update_account import *
from test_update_group import *
from test_update_metadata import *
from test_update_resource_file import *
from test_update_resource import *
from test_user_from_id import *
from test_users import *
from test_utils import *
