from .test_add_resource_files import *
from .test_copy_resource import *
from .test_bagit import *
from .test_core_metadata import *
from .test_create_account import *
from .test_create_new_version_resource import *
from .test_create_resource import *
from .test_delete_resource_file import *
from .test_delete_resource import *
from .test_get_capabilities import *
from .test_get_checksum import *
from .test_get_citation import *
from .test_get_resource_by_shortkey import *
from .test_get_resource_file import *
from .test_get_resource import *
from .test_get_resource_types import *
from .test_group_from_id import *
from .test_hstore_extra_metadata import *
from .test_publish_resource import *
from .test_resolve_doi import *
from .test_resource_file_folder_operations import *
from .test_update_account import *
from .test_update_group import *
from .test_update_metadata import *
from .test_update_resource_file import *
from .test_user_from_id import *
from .test_utils import *
