# -*- coding: utf-8 -*-
"""
Test name canonicalization
"""

from unittest import TestCase
from hs_core.search_indexes import normalize_name


class NameTest(TestCase):

    def setUp(self):
        pass

    def test_basic_canonicalization(self):
        # This is a list of names and their canonicalizations.
        names = [
            [u"Aaron Shiels", u"Shiels, Aaron"],
            [u"A. Hendrick", u"Hendrick, A."],
            [u"Alain F. Plante", u"Plante, Alain F."],
            [u"Alain F.Plante", u"Plante, Alain F."],
            [u"Alexander K. Loomis", u"Loomis, Alexander K."],
            [u"Alonso Ramírez", u"Ramírez, Alonso"],
            [u"Álvarez-Berríos, Nora L.", u"Álvarez-Berríos, Nora L."],
            [u"Anderson, B. A.", u"Anderson, B. A."],
            [u"Andrew C. Kurtz", u"Kurtz, Andrew C."],
            [u"Angel Torres-Sanchez", u"Torres-Sanchez, Angel"],
            [u"Calhoun Critical Zone Observatory", u"Calhoun Critical Zone Observatory"],
            [u"Colorado's Surface Water Conditions", u"Colorado's Surface Water Conditions"],
            [u" Damiano, S.G.", u"Damiano, S. G."],
            [u"Damiano, S. G.", u"Damiano, S. G."],
            [u"Damiano, S.G.", u"Damiano, S. G."],
            [u"Daniel deB Richter", u"Richter, Daniel deB"],
            [u"Department of Commerce (DOC)", u"Department of Commerce (DOC)"],
            [u"Duffy, Chistopher", u"Duffy, Chistopher"],
            [u"Duffy, Chris", u"Duffy, Chris"],
            [u"Duffy, Christopher J.", u"Duffy, Christopher J."],
            [u"Duncan, Jon", u"Duncan, Jon"],
            [u"Eel River CZO", u"Eel River CZO"],
            [u"G.E. Likens", u"Likens, G. E."],
            [u"Greg Barron-Gafford", u"Barron-Gafford, Greg"],
            [u"Grizelle Gonzalez", u"Gonzalez, Grizelle"],
            [u"Grizelle González", u"González, Grizelle"],
            [u"Hasenmueller, Elizabeth A.", u"Hasenmueller, Elizabeth A."],
            [u" Idaho State University", u"Idaho State University"],
            [u" IITF ", u"IITF"],
            [u"Ingo Heidbuechel", u"Ingo Heidbuechel"],  # miscategorized as corporation
            [u"Luquillo Critical Zone Observatory", u"Luquillo Critical Zone Observatory"],
            [u"M. Yekta", u"Yekta, M."],
            [u"NADP", u"NADP"],
            [u"National Ocean Service (NOS)", u"National Ocean Service (NOS)"],
            [u"National Park Service", u"National Park Service"],
            [u"Niwot Ridge LTER", u"Niwot Ridge LTER"],
            [u"NOAA", u"NOAA"],
            [u"NOAA's National Climatic Data Center", u"NOAA's National Climatic Data Center"],
            [u"Oshun, Jasper", u"Oshun, Jasper"],
            [u"others", u"others"],
            [u"Philip A.E. Pogge von Strandmann", u"Philip A.E. Pogge von Strandmann"],
            [u" Phillips, C.B. ", u"Phillips, C. B."],
            [u"Quiñones, Maya,", u"Quiñones, Maya"],
            [u"Rebecca Flournoy", u"Flournoy, Rebecca"],
            [u"Rebecca Minor", u"Minor, Rebecca"],
            [u"Rempe, Daniella", u"Rempe, Daniella"],
            [u"Rena Stair", u"Stair, Rena"],
            [u"Reynolds Creek CZO", u"Reynolds Creek CZO"],
            [u"Richardson, D.", u"Richardson, D."],
            [u"Rich Brereton", u"Brereton, Rich"],
            [u"Richter, Daniel", u"Richter, Daniel"],
            [u"Richter, Daniel deB.", u"Richter, Daniel deB."],
            [u"Richter, Daniel deB", u"Richter, Daniel deB"],
            [u"Richter, D. deB.", u"Richter, D. deB."],
            [u"Richter, D. deB", u"Richter, D. deB"],
            [u"Robert F. Stallard", u"Stallard, Robert F."],
            [u"Robert Parmenter", u"Parmenter, Robert"],
            [u"Roger Bales", u"Bales, Roger"],
            [u"Roman DiBiase", u"DiBiase, Roman"],
            [u"Rood, Dylan H.", u"Rood, Dylan H."],
            [u"Russo, Tess", u"Russo, Tess"],
            [u" Shale Hills Critical Zone Observatory", u"Shale Hills Critical Zone Observatory"],
            [u"Shale Hills Critical Zone Observatory", u"Shale Hills Critical Zone Observatory"],
            [u"Shale Hills CZO", u"Shale Hills CZO"],
            [u"Sharon Billings", u"Billings, Sharon"],
            [u"Sharon Cantrell", u"Cantrell, Sharon"],
            [u"S. Havens", u"Havens, S."],
            [u"Southern Sierra Critical Zone Observatory", u"Southern Sierra Critical Zone Observatory"],
            [u"Stone M.M.", u"Stone M.M."],
            [u"Stone, M.M.", u"Stone, M. M."],
            [u"Stromberg, Mark", u"Stromberg, Mark"],
            [u"Stroud Water Research Center", u"Stroud Water Research Center"],
            [u"Stuemky, M.", u"Stuemky, M."],
            [u"Sue Brantley", u"Brantley, Sue"],
            [u"Susan Brantley", u"Brantley, Susan"],
            [u"Susan L Brantley", u"Brantley, Susan L"],
            [u"Susan L. Brantley", u"Brantley, Susan L."],
            [u"Susan Yetter", u"Yetter, Susan"],
            [u"Sutter, Lori", u"Sutter, Lori"],
            [u"Suzanne Anderson", u"Anderson, Suzanne"],
            [u"Sweeney, B.", u"Sweeney, B."],
            [u"Szabo, Timea", u"Szabo, Timea"],
            [u"Tang, Qicheng", u"Tang, Qicheng"],
            [u"Tess Russo", u"Russo, Tess"],
            [u"Thomas, Evan", u"Thomas, Evan"],
            [u"Thomas, Evan M.", u"Thomas, Evan M."],
            [u"Thompson, A.", u"Thompson, A."],
            [u"Timothy Corley", u"Corley, Timothy"],
            [u"Timothy D. Schowalter", u"Schowalter, Timothy D."],
            [u"Todd, Dawson E.", u"Todd, Dawson E."],
            [u"Toran, Laura", u"Toran, Laura"],
            [u"Torres-Sánchez, Angel", u"Torres-Sánchez, Angel"],
            [u"Torres-Sanchez, Angel J. ", u"Torres-Sanchez, Angel J."],
            [u"T. Parzybok", u"T. Parzybok"],
            [u"Treffkorn, Jonathan", u"Treffkorn, Jonathan"],
            [u"Tsang, Y-P", u"Tsang, Y-P"],
            [u"Tyson Lee Swetnam", u"Swetnam, Tyson Lee"],
            [u"University of Arizona", u"University of Arizona"],
            [u"University of California Merced", u"University of California Merced"],
            [u"U.S. Army Corps of Engineers (USACE)", u"U.S. Army Corps of Engineers (USACE)"],
            [u"USDA-ARS", u"USDA-ARS"],
            [u"USDA USFS", u"USDA USFS"],
            [u"U.S. Department of Agriculture", u"U.S. Department of Agriculture"],
            [u"US Geological Survey", u"US Geological Survey"],
            [u"USGS", u"USGS"],
            [u"USGS NWIS", u"USGS NWIS"],
            [u"Valles Caldera National Preserve", u"Valles Caldera National Preserve"],
            [u"Wadsworth, Frank H.", u"Wadsworth, Frank H."],
            [u"Weitzman, Julie", u"Weitzman, Julie"],
            [u"West, H.", u"West, H."],
            [u"Whendee L. Silver", u"Silver, Whendee L."],
            [u"Whendee Silver", u"Silver, Whendee"],
            [u"White, Tim", u"White, Tim"],
            [u"W.H. McDowell", u"McDowell, W. H."],
            [u"William Dietrich", u"Dietrich, William"],
            [u"William G. McDowell", u"McDowell, William G."],
            [u"William H McDowell", u"McDowell, William H"],
            [u"Williams, Jennifer", u"Williams, Jennifer"],
            [u"William Wright", u"Wright, William"],
            [u"Will, R.M.", u"Will, R. M."],
            [u"W. L. Silver", u"Silver, W. L."],
            [u"Wong, Christopher S.", u"Wong, Christopher S."],
            [u"Xavier Comas", u"Comas, Xavier"],
            [u"Xavier Zapata-Rios", u"Zapata-Rios, Xavier"],
            [u"Zreda, Marek", u"Zreda, Marek"],
            [u"Z.S. Brecheisen", u"Brecheisen, Z. S."]
        ]
        for n in names:
            result = normalize_name(n[0])
            self.assertEqual(result, n[1])
