# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-07 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0042_auto_20190402_1339'),
        ('hs_tracking', '0005_auto_20170506_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='last_resource_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variable', to='hs_core.BaseResource'),
        ),
        migrations.AlterField(
            model_name='session',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='hs_tracking.Visitor'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='hs_tracking.Session'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor', to=settings.AUTH_USER_MODEL),
        ),
    ]
