# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_tracking', '0005_auto_20170506_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='resource_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
