# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0042_auto_20190402_1339'),
        ('hs_tracking', '0007_auto_20190331_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='resource_id',
            new_name='last_resource_id',
        ),
        migrations.AddField(
            model_name='variable',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hs_core.BaseResource'),
        ),
    ]
