# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-26 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_swat_modelinstance', '0007_auto_20160428_1843'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelinput',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modelinput',
            name='content_type',
        ),
        migrations.AlterUniqueTogether(
            name='modelmethod',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modelmethod',
            name='content_type',
        ),
        migrations.AlterUniqueTogether(
            name='modelobjective',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modelobjective',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='modelobjective',
            name='swat_model_objectives',
        ),
        migrations.AlterUniqueTogether(
            name='modelparameter',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modelparameter',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='modelparameter',
            name='model_parameters',
        ),
        migrations.AlterUniqueTogether(
            name='simulationtype',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='simulationtype',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='swatmodelinstancemetadata',
            name='modelinstancemetadata_ptr',
        ),
        migrations.DeleteModel(
            name='ExecutedBy',
        ),
        migrations.DeleteModel(
            name='ModelOutput',
        ),
        migrations.DeleteModel(
            name='SWATModelInstanceResource',
        ),
        migrations.DeleteModel(
            name='ModelInput',
        ),
        migrations.DeleteModel(
            name='ModelMethod',
        ),
        migrations.DeleteModel(
            name='ModelObjective',
        ),
        migrations.DeleteModel(
            name='ModelObjectiveChoices',
        ),
        migrations.DeleteModel(
            name='ModelParameter',
        ),
        migrations.DeleteModel(
            name='ModelParametersChoices',
        ),
        migrations.DeleteModel(
            name='SimulationType',
        ),
        migrations.DeleteModel(
            name='SWATModelInstanceMetaData',
        ),
    ]
