# Generated by Django 4.2.16 on 2024-10-31 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hs_tools_resource', '0021_url_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphomepageurl',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='helppageurl',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='issuespageurl',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='mailinglisturl',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='requesturlbase',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='requesturlbaseaggregation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='requesturlbasefile',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='showonopenwithlist',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='sourcecodeurl',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='supportedaggtypes',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='supportedfileextensions',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='supportedrestypes',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='supportedsharingstatus',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='testingprotocolurl',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='toolicon',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='toolversion',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='contenttypes.contenttype'),
        ),
    ]
