# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-02 15:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_tools_resource', '0021_url_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolmetadata',
            name='supported_agg_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, help_text='Aggregation types that are supported', size=None),
        ),
    ]
