# -*- coding: utf-8 -*-
"""
Test name canonicalization: This is a test and should be deleted after approval. 

"""

from django.core.management.base import BaseCommand
from hs_core.search_indexes import normalize_name

names = [
    u"A. Argerich",
    u"Aaron Shiels",
    u"Aaron Thompson",
    u"Adam Killebrew",
    u"Adam Wymore",
    u"Adrian Harpold",
    u"A. Flores",
    u"A. Hendrick",
    u"Aihua Li",
    u"Alain F. Plante",
    u"Alain F.Plante",
    u"Alexander K. Loomis",
    u"Alissa White",
    u"Alonso Ramírez",
    u"Álvarez-Berríos, Nora L.",
    u"Amrita Bhattacharyya",
    u"Anderson, B. A.",
    u"Andrew C. Kurtz",
    u"Andrew Neal",
    u"Angel Torres-Sanchez",
    u"Angie Jardine",
    u"Anne Kelly",
    u"Art F.White",
    u"Arthur, Dan K.",
    u"Ashley N. Campbell",
    u"Asmeret A. Berhe",
    u"Aufdenkampe, A. K.",
    u"Aufdenkampe, A.K.",
    u"Austin, Jason C.",
    u"Bacon, Allan R.",
    u"Bacon, Allan R",
    u"Bacon, A.R.",
    u"Baldwin, Doug",
    u"Bandelier National Monument",
    u"Barbara A. Richardson",
    u"Barbara Judy",
    u"Barger, K.",
    u"Barron-Gafford, Greg",
    u"Bassiouni, Maoya",
    u"Bawiec, W.J.",
    u"Ben Dillner",
    u"Benner, S.",
    u"Bern, Carleton",
    u"Beth Hoagland",
    u"Bhaskar Mitra",
    u"Bierman, Paul R.",
    u"Bill Dietrich",
    u"Billings, S.A.",
    u"Bill McDowell",
    u"Bills, Brian",
    u"Bishop, Jim",
    u"B. Lin",
    u"Bob Anderson",
    u"Bode, Collin",
    u"Boise Aerospace Center Laboratory",
    u" Boise State University",
    u"Boise State University",
    u"Boulder Creek Critical Zone Observatory",
    u"Brantley, Susan",
    u"Brantley, Susan L.",
    u"Brantley, Susan L",
    u"Brecheisen, Z.",
    u"Brecheisen, Zachary S.",
    u"Brecheisen, Z. S.",
    u"Brecheisen, Z.S.",
    u"Brewington, M. Lance",
    u"Brocard, Gilles",
    u"Brubaker, Kristen",
    u"Bryan Moravec",
    u"Caitlin Hodges",
    u"Caitlin Orem",
    u"Calhoun Critical Zone Observatory",
    u"Carl Heroneme",
    u"Carlos Estrada Ruiz",
    u"Carolyn Hunsaker",
    u"Carolyn Husaker",
    u"Catalina-Jemez Critical Zone Observatory",
    u"C.C. Rhoades",
    u"Charles W Cook",
    u"Chen, Chunmei",
    u"Cherkinsky, Alexander",
    u"Chester County Water Resources Authority",
    u"Chorover, Jon",
    u"Christina River Basin Critical Zone Observatory",
    u"Christine O'Connell",
    u"Christine S. O’Connell",
    u"Christof Meile",
    u"Christoph Lehmeier",
    u"Clarke, Brian",
    u"Clatyon L. Hanson",
    u"Clayton Jensen",
    u"Collin Bode",
    u"Colorado's Surface Water Conditions",
    u"Condon, Katherine E.",
    u"Cook, Charles W.",
    u"Cook, C. W.",
    u"Cook, C.W.",
    u"Coughlan, Michael R.",
    u"Craig Allen",
    u"Craig Rasmussen",
    u"Crosby, B.T.",
    u"C.W. Cook",
    u" Damiano, S.G.",
    u"Damiano, S. G.",
    u"Damiano, S.G.",
    u"Daniel deB Richter",
    u"Daniel Markewitz",
    u"Daniel Wilcox",
    u"Dan Richter",
    u"David Eissenstat",
    u"David P.Dethier",
    u"Davis, Kenneth",
    u"Davis, Kenneth J.",
    u"Dawson, Todd",
    u"Dawson, Todd E.",
    u"D. deB Richter",
    u"D. deB. Richter",
    u"Delaware Environmental Observing System (DEOS)",
    u"Department of Commerce (DOC)",
    u"Dere, Ashlee",
    u"Diana L. Karwan",
    u"Diego Barcellos",
    u"Dietrich, Bill",
    u"Dietrich, William",
    u"Dillon Ragar",
    u"D. Jean Lodge",
    u"D.M. Amatya",
    u"D. Marks",
    u"D. Martin",
    u"Domokos, Gabor",
    u"D. Riley",
    u"Duffy, Chistopher",
    u"Duffy, Chris",
    u"Duffy, Christopher J.",
    u"Duncan, Jon",
    u"Eel River CZO",
    u"E. Greathouse",
    u"Eissenstat, David",
    u"Eissenstat, David M.",
    u"Eli D. Lazarus",
    u"Elizabeth K.Coward",
    u"Emma Hauser",
    u"Enslin, Clarissa L.",
    u"Eric Parrish",
    u"Erika Gallo",
    u"Erin Berryman",
    u"Erin Stacy",
    u"Eve-Lyn Hinckley",
    u"Fain, Stephen J.",
    u"Fellows, A.W.",
    u"Fengjing Liu",
    u"Flerchinger, G.N.",
    u"Flournoy, R.",
    u"F.N. Scatena",
    u"Forest Service",
    u"Foroughi, M.",
    u"Forsythe, Brandon",
    u"Fung, Inez",
    u"Funk, D.",
    u"Gaines, Katie",
    u"G.E. Likens",
    u"Gerald N. Flerchinger",
    u"G.G. Ice",
    u"Giesen, James C.",
    u"Glenn, Nancy F",
    u"Glenn, N.F.",
    u"G. McNicol",
    u"Godsey, Sarah E.",
    u"Godsey, S.E.",
    u"Goldsmith, Steven",
    u"Gonzalez G.",
    u"González, Grizelle",
    u"Gordon R. Stephenson",
    u"Gould, William A.",
    u"Greg Barron-Gafford",
    u"Grizelle Gonzalez",
    u"Grizelle González",
    u"Guo, Qinghua",
    u"Gu, Xin",
    u"Hahm, Jesse",
    u"Hallie R. Adams",
    u"Hall, Steven",
    u"Hall, Steven J.",
    u"Hamid Dashti",
    u"Hanna Rankin",
    u"Harmon, M.A.",
    u"Hasenmueller, Elizabeth A.",
    u"Hayes, Jordan",
    u"Hayes, Jorden",
    u"Heartsil-Scalley",
    u"Heather L. Buss",
    u"Heine, P.",
    u"Heine, Paul",
    u"Heine, Paul R.",
    u"Heine, Paul R",
    u"Herndon, Elizabeth",
    u"Heroneme, C.",
    u"Hill, Lillian",
    u"Hoagland, Beth",
    u"Holly Barnard",
    u"Holly R. Barnard",
    u"Holwerda, F.",
    u"Huber, D.P.",
    u"Hyojin Kim",
    u" Idaho State University",
    u"IITF",
    u"Inez Fung",
    u"Ingo Heidbüchel",
    u"Ingo Heidbuechel",
    u"JALBTCX (Joint Airborne Lidar Bathymetry Technical Center of eXpertise)",
    u"James B Shanley",
    u"James Cullis",
    u"James Shanley",
    u"Jan A.Schuessler",
    u"Jan Hopmans",
    u"Jared Lee Wilmoth",
    u"Jared Wilmoth",
    u"Jason Kaye",
    u"J.B. Jones",
    u"J.D. Knoepp",
    u"Jemez River Basin and Santa Catalina Mountains Critical Zone Observatory",
    u"Jen Morse",
    u"Jennifer McIntosh",
    u"Jennifer Pett-Ridge",
    u"Jerolmack, Douglas",
    u"Jessica Fisher",
    u"Jessica Swetish",
    u"Jim Bishop",
    u"Jingfeng Wang",
    u"J.L. Campbell",
    u"Joanmarie Del Vecchio",
    u"Joanne M. Sharpe",
    u"Jody Potter",
    u"Johnson A.J.",
    u"Johnson, Arthur H.",
    u"Jonathan Perkins",
    u"Jon Chorover",
    u"Jon Duncan",
    u"Jon Pelletier",
    u"Julia Perdrial",
    u"Julie C. Pett-Ridge",
    u"Kaplan, L. A.",
    u"Karwan, Diana L.",
    u"Katherine Condon",
    u"Katherine E Condon",
    u"Kathleen Lohse",
    u"Kathryn Clark",
    u"Kathryn E. Clark",
    u"Kathryn Eilers",
    u"Kaye, Jason",
    u"Kaye, Margot",
    u"Keelan Barger",
    u"Ken Davis",
    u"Kenneth J. Davis",
    u"Kevin Befus",
    u"Kim Hyojin",
    u"Kim, Hyojin",
    u"King, E.K.",
    u"Kirby, Eric",
    u"Kline, F.",
    u"K. Lohse",
    u"Kormos, Patrick R.",
    u"Krystine Nelson",
    u"Kyungjin Min",
    u"Lazareva, Olesya",
    u"Lehmeier, C.A.",
    u"Leonardo V. Noto",
    u"Leon, M.",
    u"Leon, M.C.",
    u"Li, Aihua",
    u"Li, Li",
    u"Lillian Hill",
    u"Lin, Henry",
    u"Link, Percy",
    u"Link, Timothy E.",
    u"Litwin Miller, Kimberly",
    u"Lohse, K.A.",
    u"Lonneman, Michael C.",
    u"Losleben, Mark",
    u"Lucas P. Spaete",
    u"Luquillo Critical Zone Observatory",
    u"Luquillo Long-Term Ecological Research (LTER)",
    u"M.A. Callaham",
    u"Maite Guardiola-Claramonte",
    u"Majasalmi, Titta",
    u"Mallard, John",
    u"Mallard, John M.",
    u"Mallard, John McDevitt",
    u"Manuel Rosario-Torres",
    u"Marcel Schaap",
    u"Marcy Litvak",
    u"Margaret A. Burns",
    u"Maria Chapela Lara",
    u"María Chapela Lara",
    u"María Chapela-Lara",
    u"Marjorie S. Schulz",
    u"Mark D. Murdock",
    u"Markewitz, D.",
    u"Markewitz, Daniel",
    u"Mark Losleben",
    u"Marks, Danny G.",
    u"Mark S. Seyfried",
    u"Martha A. Scholl",
    u"Martha Scholl",
    u"Mary Ann Moran",
    u"Mary Key Amistadi",
    u"Mary Power",
    u"Matej Durcik",
    u"Matthais Leopold",
    u"Matthew Meadows",
    u"M.B. Adams",
    u"M. Bonnin",
    u"McCurdy, Greg",
    u"McGlynn, Brian",
    u"McNamara, James P.",
    u"Meadows, M.",
    u"Meyers, Zachary",
    u"Michael R. Willig",
    u"Miguel C Leon",
    u"Miguel Leon",
    u"Mike Goulden",
    u"Miller, Doug",
    u"Min, K.",
    u"Mitchell, Jessica J",
    u"M. Maserik",
    u"Molly Cain",
    u"M. Seyfried",
    u"Murdock, M.D.",
    u"Murphy, S.F.",
    u"Murphy, Sheila F.",
    u"M. Yekta",
    u"NADP",
    u"Naithani, Kusum",
    u"Nancy F. Glenn",
    u"Nancy Glenn",
    u"Nate Abramson",
    u"Nate Rock",
    u"Nathan Rock",
    u"National Atmospheric Deposition Program",
    u"National Center for Airborne Laser Mapping",
    u"National Oceanic and Atmospheric Administration (NOAA)",
    u"National Ocean Service (NOS)",
    u"National Park Service",
    u"Nawal, C.",
    u"Nayani Ilangakoon",
    u"NCALM",
    u"Neal, Andrew",
    u"Nelson, Donald",
    u"Nelson, Donald R.",
    u"Newbold, J. D.",
    u"Newbold, J.D.",
    u"Nicolas Perdrial",
    u"Niu, Xianzeng",
    u"Niwot Ridge LTER",
    u"NOAA",
    u"NOAA Climate Reference Network (CRN)",
    u"NOAA's National Climatic Data Center",
    u"Noah Finnegan",
    u"Noah Molotch",
    u"Office for Coastal Management (OCM)",
    u"Oliver W. Moore",
    u"Olsoy, Peter J",
    u"O’Neill, Katherine P.",
    u"O'Neill, K. P.",
    u"Oshun, Jasper",
    u"others",
    u"Pamela L. Sullivan",
    u"Parsons, S.B.",
    u"Patrick Broxton",
    u"Patrick Kelly",
    u"Patton, N.",
    u"Patton, N.R.",
    u"Paul Brooks",
    u"Peter Hartsough",
    u"Peter Kirchner",
    u"Peter S. Nico",
    u"Peter Troch",
    u"Pett-Ridge, J.C.",
    u"Pett-Ridge, Julie",
    u"Philip A.E. Pogge von Strandmann",
    u"Phillips, C.B.",
    u"Pierce, J.",
    u"P. Kormos",
    u"Plante A.F.",
    u"Plante, A.F.",
    u"P.M. Wohlgemuth",
    u"Porder, S.",
    u"Porder, Stephen",
    u"Power, Mary",
    u"P.R. Heine",
    u"Qicheng Tang",
    u"Qinghua Guo",
    u"Quiñones, Maya,",
    u"Rebecca Flournoy",
    u"Rebecca Minor",
    u"Rempe, Daniella",
    u"Rena Stair",
    u"Reynolds Creek Critical Zone Observatory",
    u"Reynolds Creek CZO",
    u"Richardson, D.",
    u"Rich Brereton",
    u"Richter, Daniel",
    u"Richter, Daniel deB.",
    u"Richter, Daniel deB",
    u"Richter, D. deB.",
    u"Richter, D. deB",
    u"Robert F. Stallard",
    u"Robert Parmenter",
    u"Roger Bales",
    u"Roman DiBiase",
    u"Rood, Dylan H.",
    u"Russo, Tess",
    u"Ryland, Rachel",
    u"Ryland, Rachel C.",
    u"Sabina Shahnaz",
    u"Salve, Rohit",
    u"Samantha Elledge",
    u"Samik Bagchi",
    u"San Juan Ultra",
    u"Sara Harders",
    u"Satish Bastola",
    u"Scatena, F.N.",
    u"Scholl, M.A.",
    u"Scholl, Martha A.",
    u"Schroeder, Paul A.",
    u"Scott Compton",
    u"Scott Hynek",
    u"S.D. Sebestyen",
    u"Seyfried, Mark S.",
    u"Seyfried, M.S.",
    u" Shale Hills Critical Zone Observatory",
    u"Shale Hills Critical Zone Observatory",
    u"Shale Hills CZO",
    u"Sharon Billings",
    u"Sharon Cantrell",
    u"S. Havens",
    u"Shawn Alexander Pedron",
    u"Sheila F. Murphy",
    u"Shirley Papuga",
    u"Shi, Yuning",
    u"Shrestha, Rupesh",
    u"Shuttleworth, William J.",
    u"Silver, Whendee L.",
    u"Singha, Kamini",
    u"Slingerland, Rudy",
    u"S.L. Johnson",
    u"Smith, Lauren",
    u"Southern Sierra Critical Zone Observatory",
    u"Spaete, L.P.",
    u"Stacy, E.",
    u"Stallard, R.F.",
    u"Stanbery, C.",
    u"Steel, Peter",
    u"Steven Glaser",
    u"Steven Henning",
    u"Steven J. Hall",
    u"Steven S. Van Vactor",
    u"Stone M.M.",
    u"Stone, M.M.",
    u"Stromberg, Mark",
    u"Stroud Water Research Center",
    u"Stuemky, M.",
    u"Sue Brantley",
    u"Susan Brantley",
    u"Susan L Brantley",
    u"Susan L. Brantley",
    u"Susan Yetter",
    u"Sutter, Lori",
    u"Suzanne Anderson",
    u"Sweeney, B.",
    u"Szabo, Timea",
    u"Tang, Qicheng",
    u"Tess Russo",
    u"Thomas, Evan",
    u"Thomas, Evan M.",
    u"Thompson, A.",
    u"Timothy Corley",
    u"Timothy D. Schowalter",
    u"Todd, Dawson E.",
    u"Toran, Laura",
    u"Torres-Sánchez, Angel",
    u"Torres-Sanchez, Angel J. ",
    u"T. Parzybok",
    u"Treffkorn, Jonathan",
    u"Tsang, Y-P",
    u"Tyson Lee Swetnam",
    u"University of Arizona",
    u"University of California Merced",
    u"U.S. Army Corps of Engineers (USACE)",
    u"USDA-ARS",
    u"USDA ARS Northwest Watershed Research Center",
    u"USDA-ARS Northwest Watershed Research Center",
    u"USDA USFS",
    u"U.S. Department of Agriculture",
    u"US Geological Survey",
    u"US Geological Survey Caribbean Water Science Center",
    u"USGS",
    u"USGS National Water Information System",
    u"USGS NWIS",
    u"Valles Caldera National Preserve",
    u"Wadsworth, Frank H.",
    u"Weitzman, Julie",
    u"West, H.",
    u"Whendee L. Silver",
    u"Whendee Silver",
    u"White, Tim",
    u"W.H. McDowell",
    u"William Dietrich",
    u"William G. McDowell",
    u"William H McDowell",
    u"William H. McDowell",
    u"Williams, Cameron",
    u"Williams, Jennifer",
    u"William Wright",
    u"Will, R.M.",
    u"W. L. Silver",
    u"Wong, Christopher S.",
    u"Xavier Comas",
    u"Xavier Zapata-Rios",
    u"Xiande Meng",
    u"Xiao, Dacheng",
    u"Xing Hao",
    u"Xing, Hao Xing",
    u"Yan Lin",
    u"Yannis Dialynas",
    u"Yao Tang",
    u"Yawen Shen",
    u"Yuting He,",
    u"Yu, Xuan",
    u"Zachary Brecheisen",
    u"Zhuo Wang",
    u"Zreda, Marek",
    u"Z.S. Brecheisen"
]


class Command(BaseCommand):
    help = "Results of name canonicalization for review by @cuahsimarko"

    def handle(self, *args, **options):
        for n in names:
            output = normalize_name(n)
            if not isinstance(output, unicode):
                print("output is str")
            if n != output:
                print(output + "|" + n)
            else:
                print(n)
