#!/bin/bash

# Run migrations separately for django 1.7
# specific to running in PyCharm on local machine (due to sshd)

sleep 3s
echo "made sure postgis was enabled on PostgreSQL"
psql -U postgres -h postgis -w -c 'create extension postgis;'
/usr/sbin/sshd
uwsgi --socket :8001 --ini uwsgi.ini