# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-11 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_model_program', '0006_auto_20151216_1511'),
        ('hs_modelinstance', '0007_auto_20220803_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelprogrammetadata',
            name='coremetadata_ptr',
        ),
        migrations.RemoveField(
            model_name='mpmetadata',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ModelProgramResource',
        ),
        migrations.DeleteModel(
            name='ModelProgramMetaData',
        ),
        migrations.DeleteModel(
            name='MpMetadata',
        ),
    ]
