# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSDMSName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(editable=False, help_text='The source file from CSDMS', max_length=256)),
                ('part', models.CharField(choices=[('name', 'name'), ('decoration', 'decoration'), ('measure', 'measure')], help_text='The standard names can be splitted to three parts,                                       name, decoration, and measurement', max_length=16)),
                ('value', models.CharField(editable=False, help_text='The value for the corresponding part', max_length=255)),
            ],
        ),
    ]
