# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-25 17:46
from __future__ import unicode_literals

from django.db import migrations
from hs_csdms.utils import split_csdms_names


def populate_csdms_names(apps, schema_editor):
    """ Store each part from split_csdms into LDAWord model
    """
    csdms_names, csdms_decors, csdms_measures = split_csdms_names()
    CSDMSName = apps.get_model('hs_csdms', 'CSDMSName')
    for csdms_name in csdms_names:
        if len(csdms_name) > 1:
            csdms_record = CSDMSName()
            csdms_record.source = 'CSDMSName'
            csdms_record.part = 'name'
            csdms_record.value = csdms_name
            csdms_record.save()

    for csdms_decor in csdms_decors:
        if len(csdms_decor) > 1:
            csdms_record = CSDMSName()
            csdms_record.source = 'CSDMSName'
            csdms_record.part = 'decoration'
            csdms_record.value = csdms_decor
            csdms_record.save()

    for csdms_measure in csdms_measures:
        if len(csdms_measure) > 1:
            csdms_record = CSDMSName()
            csdms_record.source = 'CSDMSName'
            csdms_record.part = 'measure'
            csdms_record.value = csdms_measure
            csdms_record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hs_csdms', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(populate_csdms_names),
    ]
