# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-28 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_app_netCDF', '0007_netcdfmetadata_is_dirty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netcdfmetadata',
            name='coremetadata_ptr',
        ),
        migrations.DeleteModel(
            name='NetcdfResource',
        ),
        migrations.DeleteModel(
            name='NetcdfMetaData',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='originalcoverage',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='originalcoverage',
                    name='content_type',
                ),
                migrations.RemoveField(
                    model_name='variable',
                    name='content_type',
                ),
                migrations.DeleteModel(
                    name='OriginalCoverage',
                ),
                migrations.DeleteModel(
                    name='Variable',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='OriginalCoverage',
                    table='hs_file_types_originalcoverage',
                ),
                migrations.AlterModelTable(
                    name='Variable',
                    table='hs_file_types_variable',
                ),
            ],
        ),
    ]
