# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_app_netCDF', '0007_netcdfmetadata_is_dirty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetcdfResource',
        ),
    ]
