# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-09 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_script_resource', '0002_repo_charfield_to_urlfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptmetadata',
            name='coremetadata_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='scriptspecificmetadata',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='scriptspecificmetadata',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ScriptResource',
        ),
        migrations.DeleteModel(
            name='ScriptMetaData',
        ),
        migrations.DeleteModel(
            name='ScriptSpecificMetadata',
        ),
    ]
