# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-23 16:21


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ODM2Variable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        editable=False, help_text="Variable name", max_length=256
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        editable=False, help_text="Definition of variable name"
                    ),
                ),
            ],
        ),
    ]
