# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-23 16:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_odm2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odm2variable',
            old_name='description',
            new_name='definition',
        ),
        migrations.AddField(
            model_name='odm2variable',
            name='provenance_uri',
            field=models.TextField(blank=True, editable=False, help_text='URI describing provenance of variable name'),
        ),
        migrations.AddField(
            model_name='odm2variable',
            name='resource_uri',
            field=models.TextField(blank=True, editable=False, help_text='URI of variable name relative to ODM2 server'),
        ),
    ]
