# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_geo_raster_resource', '0006_auto_20161129_0121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RasterResource',
        ),
    ]
