# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hs_core.hs_rdf


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hs_geo_raster_resource', '0006_auto_20161129_0121'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='OriginalCoverageRaster',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('object_id', models.PositiveIntegerField()),
                        ('_value', models.CharField(max_length=10000, null=True)),
                        ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_geo_raster_resource_originalcoverageraster_related', to='contenttypes.ContentType')),
                    ],
                    bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
                ),
                migrations.AlterUniqueTogether(
                    name='originalcoverage',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='originalcoverage',
                    name='content_type',
                ),
                migrations.DeleteModel(
                    name='OriginalCoverage',
                ),
                migrations.AlterUniqueTogether(
                    name='originalcoverageraster',
                    unique_together=set([('content_type', 'object_id')]),
                ),
            ],
            database_operations=[
                migrations.RenameModel("OriginalCoverage", "OriginalCoverageRaster")
            ]
        )
    ]
