# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-06 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_geo_raster_resource', '0007_auto_20220302_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rastermetadata',
            name='coremetadata_ptr',
        ),
        migrations.DeleteModel(
            name='RasterResource',
        ),
        migrations.DeleteModel(
            name='RasterMetaData',
        ),

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='bandinformation',
                    name='content_type',
                ),
                migrations.AlterUniqueTogether(
                    name='cellinformation',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='cellinformation',
                    name='content_type',
                ),
                migrations.AlterUniqueTogether(
                    name='originalcoverageraster',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='originalcoverageraster',
                    name='content_type',
                ),
                migrations.DeleteModel(
                    name='BandInformation',
                ),
                migrations.DeleteModel(
                    name='CellInformation',
                ),
                migrations.DeleteModel(
                    name='OriginalCoverageRaster',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='BandInformation',
                    table='hs_file_types_bandinformation',
                ),
                migrations.AlterModelTable(
                    name='CellInformation',
                    table='hs_file_types_cellinformation',
                ),
                migrations.AlterModelTable(
                    name='OriginalCoverageRaster',
                    table='hs_file_types_originalcoverageraster',
                ),
            ],
        )
    ]
