#!/bin/bash

mkdir /tmp/media
pushd $PWD
HSDIR=$PWD
cd /tmp
cp $HSDIR/scripts/rsync-media-prod ./rsync-media-prod.exp
chmod +x rsync-media-prod.exp
./rsync-media-prod.exp
cd media
tar -czf "media-hydroshare-`date +"%m-%d-%y"`.tar.gz" media
cp "media-hydroshare-`date +"%m-%d-%y"`.tar.gz" $HSDIR
popd
rm /tmp/rsync-media-prod.exp
rm -rf /tmp/media