#!/usr/bin/env bash

# remove-root-items
# Author: Michael Stealey <michael.j.stealey@gmail.com>

find /hydroshare -user root -ls | rev | cut -d ' ' -f 1 | rev > root-items.txt

echo "CHOWN files owned by root"
while read line ; do
    echo "  - chown -R hydro-service:storage-hydro ${line}"
    chown -R hydro-service:storage-hydro ${line};
done < root-items.txt

exit 0;