#!/usr/bin/env bash

# fuse-init
# Author: Michael Stealey <michael.j.stealey@gmail.com>

display_usage() {
	echo "Usage: $0 local/PATH [iRODS/PATH] ..."
	echo "FUSE mount local directory to an iRODS resource/collection"
	echo " local/PATH - PATH in local file system"
	echo "Optional"
	echo " iRODS/PATH - PATH in iRODS space that will be mount to local/PATH"
}

# get iRODS credentials from local_settings.py
get_irods_settings() {
    cat hydroshare/local_settings.py | grep IRODS_HOST | rev | cut -d ' ' -f -1 | rev | tr -d "'" > IRODS_CONFIG
    cat hydroshare/local_settings.py | grep IRODS_PORT | rev | cut -d ' ' -f -1 | rev | tr -d "'" >> IRODS_CONFIG
    cat hydroshare/local_settings.py | grep IRODS_USERNAME | rev | cut -d ' ' -f -1 | rev | tr -d "'" >> IRODS_CONFIG
    cat hydroshare/local_settings.py | grep IRODS_ZONE | rev | cut -d ' ' -f -1 | rev | tr -d "'" >> IRODS_CONFIG
    cat hydroshare/local_settings.py | grep IRODS_AUTH | rev | cut -d ' ' -f -1 | rev | tr -d "'" >> IRODS_CONFIG
}

# clear previous credential files
check_previous_credentials() {
    if [[ -f ~/.irods/irods_environment.json ]]; then
        echo "*** INFO: Removing file - ~/.irods/irods_environment.json ***"
        rm ~/.irods/irods_environment.json;
    fi
    if [[ -f ~/.irods/.irodsA ]]; then
        echo "*** INFO: Removing file - ~/.irods/.irodsA ***"
        rm ~/.irods/.irodsA;
    fi
}

# FUSE mount the specified directory with the iRODS credentials
    fuse_mount_resource() {
    if [[ ! -d "${1}" ]]; then
        echo "*** INFO: Creating directory ${1} for FUSE mount ***"
        mkdir -p ${1};
    else
        echo "*** INFO: Attempting to remove previous FUSE mount if it exists ***"
        fusermount -u ${1};
    fi
    echo "*** INFO: FUSE mounting iRODS: $(ipwd) files to local: ${1} ***"
    irodsFs ${1}
}

# validate input from user
if [[  $# -ne 1 ]] && [[ $# -ne 2 ]]; then
    display_usage
    exit 1;
elif [[ $# -eq 1 ]]; then
    get_irods_settings
    check_previous_credentials
    iinit < IRODS_CONFIG
    echo "*** INFO: FUSE mount default iRODS:$(ipwd) to ${1} ***"
    fuse_mount_resource $1;
else
    get_irods_settings
    check_previous_credentials
    iinit < IRODS_CONFIG
    echo "*** INFO: Attempting to icd to ${2} ***"
    TRY_ICD=$(icd ${2})
    if [[ "${TRY_ICD}" == *"No such directory (collection):"* ]]; then
        echo "*** WARNING: No such directory (collection) found ***"
        echo "*** Exiting without attempting mount ***"
        exit 1;
    fi
    fuse_mount_resource $1;
fi

exit 0;