#!/usr/bin/env bash

# pre-remove-hs
# Author: Michael Stealey <michael.j.stealey@gmail.com>

echo "  - docker exec hydroshare /usr/bin/env bash scripts/remove-root-items"
docker exec hydroshare /usr/bin/env bash scripts/remove-root-items

exit 0;