#!/usr/bin/env bash

# remove-root-items
# Author: Michael Stealey <michael.j.stealey@gmail.com>

echo "REMOVE: root owned files"
find /hydroshare -user root -ls | rev | cut -d ' ' -f 1 | rev > root-items.txt

while read line ; do
    echo "  - rm -rf ${line}"
    rm -rf ${line};
done < root-items.txt

exit 0;