#!/usr/bin/env bash

# remove-root-items
# Author: Michael Stealey <michael.j.stealey@gmail.com>

find /hydroshare -user root -ls | rev | cut -d ' ' -f 1 | rev > root-items.txt

while read line ; do
    echo "*** REMOVE: ${line} ***"
    rm -rf $line;
done < root-items.txt

exit 0;