#!/bin/bash

# remove-hs

# set local variables
### hydrodev VM
HS_PATH=/home/${USER}/hydroshare
BACKUP_PATH=/home/${USER}/backup
### custom settings (Linux, OS X, etc.)
#HS_PATH=/Users/${USER}/Github/hydroshare
#BACKUP_PATH=/Users/${USER}/Github/backup

# set variables for use in script
FIG_VER=$(fig --version)
DC_VER=$(docker-compose --version)
CID=$(docker ps -a | grep hydroshare_hydroshare_1 | cut -d ' ' -f 1)
MEDIA_FILES=${HS_PATH}/media_files

# remove media directory from hydroshare container
docker exec $CID rm -rf /home/docker/hydroshare/hydroshare/static/media/

# remove entire hydroshare directory
echo "*** remove ${HS_PATH}/hydroshare ***"
cd $HS_PATH
cd ../
rm -rf hydroshare/

echo "*** FINISHED SCRIPT remove-hs ***"
exit;