#!/usr/bin/env bash

# remove-root-items
# Author: Michael Stealey <michael.j.stealey@gmail.com>

find /home/docker/hydroshare -user root -ls | tr -s ' ' | cut -d ' ' -f 12 > root-items.txt

while read line ; do
    echo "*** REMOVE: ${line} ***"
    rm -rf $line;
done < root-items.txt

exit 0;