#!/usr/bin/expect -f

# connect via scp
spawn scp -r -P 1338 media root@localhost:/home/docker/hydroshare/hydroshare/static
# Expect either add fingerprint and/or enter password
expect {
	-re ".*es.*o.*" {
		exp_send "yes\r"
		exp_continue
	}
	-re ".*sword.*" {
		exp_send "docker\r"
	}
}
interact
