#!/usr/bin/env bash

# postDumpMigrationFiles
# Author: Michael Stealey <michael.j.stealey@gmail.com>

### How to use
# from the migration-scripts directory: $ ./postDumpMigrationFiles

echo "*** remove dump scripts from hydroshare directory ***"
rm ../dumpResourceToJSON.py
rm ../dumpCommentsToJSON.py
rm ../dumpThreadedCommentsToJSON.py
rm ../dumpRatingsToJSON.py
rm ../dumpMigrationFiles
echo "*** remove dump files from hydroshare directory (leave only migration-files tar archive) ***"
rm ../comments.json
rm ../rating.json
rm ../resources.json
rm ../threaded_comments.json
rm ../user.json
rm ../userprofile.json
rm ../media.migration.tar.gz
rm ../pg.migration.sql

exit 0;