#!/usr/bin/env bash

# run-nginx
# Author: Michael Stealey <michael.j.stealey@gmail.com>

### Load Configuration Variables ###
export NGINX_CONFIG_DIRECTORY='./config-files'
export NGINX_DOCKER_IMG='nginx:1.11'
export NGINX_DOCKER_CNTR='nginx'

display_usage() {
	echo "*** run-nginx control script ***"
	echo "usage: $0 restart     # restarts docker nginx"
	echo "usage: $0 start       # starts docker nginx"
	echo "usage: $0 stop        # stops docker nginx"
	echo "usage: $0 maint_on    # turn on  maintenance mode"
	echo "usage: $0 maint_off   # turn off maintenance mode"
}

preflight_nginx() {
    echo "PREFLIGHT NGINX:"
    yes | cp -rf ${NGINX_CONFIG_DIRECTORY}/hydroshare-ssl-nginx.conf.template ${NGINX_CONFIG_DIRECTORY}/hs-nginx.conf
    sed -i 's/FQDN_OR_IP/'${FQDN_OR_IP}'/g' ${NGINX_CONFIG_DIRECTORY}/hs-nginx.conf
    sed -i 's/CURRENT_VM/'${CURRENT_VM}'/g' ${NGINX_CONFIG_DIRECTORY}/hs-nginx.conf
    sed -i 's/SSL_CERT_FILE/'${SSL_CERT_FILE}'/g' ${NGINX_CONFIG_DIRECTORY}/hs-nginx.conf
    sed -i 's/SSL_KEY_FILE/'${SSL_KEY_FILE}'/g' ${NGINX_CONFIG_DIRECTORY}/hs-nginx.conf;
    cp server_error_on.html static/server_error_on.html
}

stop_nginx() {
    echo "STOP NGINX:"
    docker-compose down
#    docker rm -f ${NGINX_DOCKER_CNTR}
}

start_nginx() {
    echo "START NGINX:"
    preflight_nginx
    docker-compose up -d
    docker ps -a
}

restart_nginx() {
    echo "RESTART NGINX:"
    stop_nginx STOP
    start_nginx START
}

maint_on_nginx() {
    echo "MAINTENANCE MODE ON:"
    echo "  - cp maintenance_on.html static/maintenance_on.html"
    cp maintenance_on.html static/maintenance_on.html
}

maint_off_nginx() {
    echo "MAINTENANCE MODE OFF:"
    echo "  - rm static/maintenance_on.html"
    rm static/maintenance_on.html
}

### Display usage if exactly one argument is not provided ###
if [  $# -ne 1 ]
then
    display_usage
    exit 1
fi

case "$1" in
    restart) restart_nginx $1
        ;;
      start) start_nginx   $1
        ;;
       stop) stop_nginx    $1
        ;;
   maint_on) maint_on_nginx
        ;;
  maint_off) maint_off_nginx
        ;;
    *) display_usage
        ;;
esac

exit 0;
