# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-03 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_irods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodsenvironment',
            name='auth',
            field=models.TextField(verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='rodsenvironment',
            name='cwd',
            field=models.TextField(verbose_name='Working directory'),
        ),
        migrations.AlterField(
            model_name='rodsenvironment',
            name='def_res',
            field=models.CharField(max_length=255, verbose_name='Default resource'),
        ),
        migrations.AlterField(
            model_name='rodsenvironment',
            name='home_coll',
            field=models.CharField(max_length=255, verbose_name='Home collection'),
        ),
        migrations.AlterField(
            model_name='rodsenvironment',
            name='host',
            field=models.CharField(max_length=255, verbose_name='Hostname'),
        ),
    ]
