# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_irods', '0002_auto_20200507_0037'),
        ('django_irods', '0002_auto_20200603_2110'),
    ]

    operations = [
    ]
