# Generated by Django 3.2.25 on 2024-08-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_irods', '0002_auto_20200603_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='AVU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('attName', models.TextField()),
                ('attVal', models.TextField()),
            ],
            options={
                'verbose_name': 'AVU',
            },
        ),
        migrations.AddConstraint(
            model_name='avu',
            constraint=models.UniqueConstraint(fields=('name', 'attName'), name='unique_avu'),
        ),
    ]
