# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_ts', '0004_auto_20160114_0252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefTimeSeriesResource',
        ),
    ]
