# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-02 18:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion

import hs_core.hs_rdf


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hs_app_timeseries', '0003_auto_20180623_2049'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='VariableTimeseries',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('object_id', models.PositiveIntegerField()),
                        ('series_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), default=[], size=None)),
                        ('is_dirty', models.BooleanField(default=False)),
                        ('variable_code', models.CharField(max_length=50)),
                        ('variable_name', models.CharField(max_length=100)),
                        ('variable_type', models.CharField(max_length=100)),
                        ('no_data_value', models.IntegerField()),
                        ('variable_definition', models.CharField(blank=True, max_length=255, null=True)),
                        ('speciation', models.CharField(blank=True, max_length=255, null=True)),
                        ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_app_timeseries_variabletimeseries_related', to='contenttypes.ContentType')),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=(models.Model, hs_core.hs_rdf.RDF_Term_MixIn),
                ),
                migrations.RemoveField(
                    model_name='variable',
                    name='content_type',
                ),
                migrations.DeleteModel(
                    name='Variable',
                ),
            ],
            database_operations=[
                migrations.RenameModel("Variable", "VariableTimeseries")
            ]
        )
    ]
