/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthRedirect: typeof import('./components/account/auth-redirect.vue')['default']
    'Cd.footer': typeof import('./components/base/cd.footer.vue')['default']
    'Cd.rangeInput': typeof import('./components/search-results/cd.range-input.vue')['default']
    'Cd.search': typeof import('./components/search/cd.search.vue')['default']
    'Cd.searchMap': typeof import('./components/search-results/cd.search-map.vue')['default']
    'Cd.searchResults': typeof import('./components/search-results/cd.search-results.vue')['default']
    'Cd.searchSidebar': typeof import('./components/search-results/cd.search-sidebar.vue')['default']
    'Cd.spatialCoverageMap': typeof import('./components/search-results/cd.spatial-coverage-map.vue')['default']
    'Cz.login': typeof import('./components/account/cz.login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
