/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthRedirect: typeof import('./components/account/auth-redirect.vue')['default']
    'Cd.authorProfile': typeof import('./components/landing-page/cd.author-profile.vue')['default']
    'Cd.footer': typeof import('./components/base/cd.footer.vue')['default']
    'Cd.manageAccess': typeof import('./components/landing-page/cd.manage-access.vue')['default']
    'Cd.ownerProfile': typeof import('./components/landing-page/cd.owner-profile.vue')['default']
    'Cd.rangeInput': typeof import('./components/search-results/cd.range-input.vue')['default']
    'Cd.readmeEditor': typeof import('./components/landing-page/cd.readme-editor.vue')['default']
    'Cd.search': typeof import('./components/search/cd.search.vue')['default']
    'Cd.searchMap': typeof import('./components/search-results/cd.search-map.vue')['default']
    'Cd.searchResults': typeof import('./components/search-results/cd.search-results.vue')['default']
    'Cd.searchSidebar': typeof import('./components/search-results/cd.search-sidebar.vue')['default']
    'Cd.spatialCoverageMap': typeof import('./components/search-results/cd.spatial-coverage-map.vue')['default']
    'Cz.login': typeof import('./components/account/cz.login.vue')['default']
    EditDataset: typeof import('./components/landing-page/edit-dataset.vue')['default']
    HsUppy: typeof import('./components/landing-page/hs-uppy.vue')['default']
    LandingPage: typeof import('./components/landing-page/landing-page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toc: typeof import('./components/base/toc.vue')['default']
  }
}
