# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-26 20:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0015_auto_20200603_2110"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_1",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '999999999'. Up to 16 digits allowed.",
                        regex="^\\d{8,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_2",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '999999999'. Up to 16 digits allowed.",
                        regex="^\\d{8,15}$",
                    )
                ],
            ),
        ),
    ]
