# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-17 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import theme.utils


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0017_phone_validation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=theme.utils.get_upload_path_userprofile),
        ),
    ]
