# Generated by Django 3.2.15 on 2022-09-22 14:00

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0019_auto_20220510_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='has_social_network_links',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identifiers',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True),
        ),
    ]
