# Generated by Django 3.2.15 on 2022-12-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0020_auto_20220922_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_1',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
