# Generated by Django 3.2.15 on 2023-04-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0021_auto_20221229_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subject_areas',
            field=models.CharField(blank=True, help_text='A comma-separated list of subject areas you are interested in researching. e.g.             "Computer Science, Hydrology, Water Management"', max_length=1024, null=True),
        ),
    ]
