# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 04:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0021_auto_20210423_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_1',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 16 digits allowed.", regex='^\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_2',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 16 digits allowed.", regex='^\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subject_areas',
            field=models.CharField(blank=True, help_text='A comma-separated list of subject areas you are interested in researching. e.g. "Computer Science, Hydrology, Water Management"', max_length=1024, null=True),
        ),
    ]
