# Generated by Django 3.2.15 on 2023-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0022_alter_userprofile_subject_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subject_areas',
            field=models.CharField(blank=True, help_text='A list of subject areas you are interested in researching. e.g. "Water Management." Free text entry or select from the suggestions', max_length=1024, null=True),
        ),
    ]
