# Generated by Django 3.2.19 on 2023-11-01 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0023_alter_userprofile_subject_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotamessage',
            name='published_resource_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
