# Generated by Django 3.2.19 on 2023-11-05 17:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme', '0024_quotamessage_published_resource_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(blank=True, max_length=300, null=True)),
                ('storage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('org_info', models.TextField(blank=True, max_length=100, null=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2qrequest', to='theme.userquota')),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ru2qrequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
