# Generated by Django 3.2.19 on 2023-11-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0025_quotarequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotarequest',
            name='redeemed',
        ),
        migrations.AddField(
            model_name='quotarequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('denied', 'denied'), ('approved', 'approved'), ('revoked', 'revoked')], default='pending', max_length=20),
        ),
    ]
