# Generated by Django 3.2.19 on 2023-11-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0026_auto_20231106_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotarequest',
            name='org_info',
        ),
    ]
