# Generated by Django 3.2.20 on 2024-01-04 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0027_remove_quotarequest_org_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotarequest',
            name='justification',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(15, 'must contain at least 15 characters'), django.core.validators.MaxLengthValidator(300, 'maximum 300 characters')]),
        ),
        migrations.AlterField(
            model_name='quotarequest',
            name='storage',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
