# Generated by Django 3.2.20 on 2024-01-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0029_auto_20240118_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquota',
            name='remaining_grace_period',
        ),
        migrations.AddField(
            model_name='userquota',
            name='grace_period_ends',
            field=models.DateField(blank=True, default=None, help_text='The date that Grace Period will end for this User Quota', null=True, verbose_name='Remaining Grace Period'),
        ),
        migrations.AlterField(
            model_name='quotamessage',
            name='content',
            field=models.TextField(default='You can request additional quota, from your User Profile. We will try to accommodate reasonable requests for additional quota. If you have a large quota request you may need to contribute toward the costs of providing the additional space you need. See https://help.hydroshare.org/about-hydroshare/policies/quota/ for more information about the quota policy.'),
        ),
    ]
