# Generated by Django 3.2.20 on 2024-02-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0031_auto_20240201_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquota',
            name='grace_period_ends',
            field=models.DateField(blank=True, default=None, help_text='The date that Grace Period will end for this User Quota', null=True, verbose_name='Grace Period Ends'),
        ),
    ]
