# Generated by Django 3.2.24 on 2024-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0033_auto_20240201_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotamessage',
            name='quota_usage_info',
            field=models.TextField(default='Your quota for HydroShare resources is {allocated}{unit}. You currently have resources that consume {used}{unit}, {percent}% of your quota. '),
        ),
        migrations.AlterField(
            model_name='quotamessage',
            name='content',
            field=models.TextField(default='You can request additional quota, from your User Profile. We will try to accommodate reasonable requests for additional quota. If you have a large quota request you may need to contribute toward the costs of providing the additional space you need. '),
        ),
        migrations.AlterField(
            model_name='quotamessage',
            name='enforce_content_prepend',
            field=models.TextField(default='You can not take further action because you have exceeded your quota. '),
        ),
        migrations.AlterField(
            model_name='quotamessage',
            name='grace_period_content_prepend',
            field=models.TextField(default='You have exceeded your HydroShare quota. You have a grace period until {cut_off_date} to reduce your use to below your quota, or to acquire additional quota, after which you will no longer be able to create new resources in HydroShare. '),
        ),
        migrations.AlterField(
            model_name='quotamessage',
            name='warning_content_prepend',
            field=models.TextField(default='Once your quota reaches 100% you will no longer be able to create new resources in HydroShare. '),
        ),
    ]
