# Generated by Django 3.2.25 on 2024-04-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0034_auto_20240312_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquota',
            name='data_zone_value',
        ),
    ]
