# Generated by Django 3.2.25 on 2024-07-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('theme', '0036_auto_20240702_1847'), ('theme', '0037_remove_userprofile_create_irods_user_account')]

    dependencies = [
        ('theme', '0035_remove_userquota_data_zone_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquota',
            name='user_zone_value',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='create_irods_user_account',
        ),
    ]
