# Generated by Django 3.2.25 on 2024-07-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('theme', '0036_auto_20240702_1847'), ('theme', '0037_remove_userprofile_create_irods_user_account')]

    dependencies = [
        ('theme', '0035_remove_userquota_data_zone_value'),
    ]

    operations = [
        # make some fields nullable
        migrations.AlterField(
            model_name='userprofile',
            name='create_irods_user_account',
            field=models.BooleanField(default=False, help_text='Check to create an iRODS user account in HydroShare user iRODS space for staging large files (>2GB) using iRODS clients such as Cyberduck (https://cyberduck.io/) and icommands (https://docs.irods.org/master/icommands/user/).Uncheck to delete your iRODS user account. Note that deletion of your iRODS user account deletes all of your files under this account as well.', null=True),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='user_zone_value',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='userquota',
                    name='user_zone_value',
                ),
                migrations.RemoveField(
                    model_name='userprofile',
                    name='create_irods_user_account',
                ),
            ],
            # Operations to be performed later on the database.
            database_operations=[
                # migrations.RunSQL(
                #     sql='ALTER TABLE "theme_userquota" DROP COLUMN "user_zone_value" CASCADE;',
                #     reverse_sql='ALTER TABLE "theme_userquota" ADD COLUMN "user_zone_value" varchar(255) NULL;',
                # ),
                # migrations.RunSQL(
                #     sql='ALTER TABLE "theme_userprofile" DROP COLUMN "create_irods_user_account" CASCADE;',
                #     reverse_sql='ALTER TABLE "theme_userprofile" ADD COLUMN "create_irods_user_account" boolean NOT NULL;',
                # ),
            ]
        )
    ]