# Generated by Django 3.2.25 on 2024-07-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0035_remove_userquota_data_zone_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquota',
            name='user_zone_value',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_irods_user_account',
            field=models.BooleanField(default=False, help_text='Has an iRODS user account been created in HydroShare user iRODS space for staging large files (>2GB) using iRODS clients such as Cyberduck (https://cyberduck.io/) and icommands (https://docs.irods.org/master/icommands/user/).Uncheck after requesting your iRODS user account be deleted. Note that deletion of your iRODS user account deletes all of your files under this account as well.'),
        ),
    ]
