# Generated by Django 3.2.25 on 2024-05-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0035_remove_userquota_data_zone_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotamessage',
            name='published_resource_percent',
        ),
    ]
