# Generated by Django 3.2.25 on 2024-07-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0036_auto_20240702_1847_squashed_0037_remove_userprofile_create_irods_user_account'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
            ],
            # Operations to be performed on the database.
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "theme_userquota" DROP COLUMN "user_zone_value" CASCADE;',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "theme_userprofile" DROP COLUMN "create_irods_user_account" CASCADE;',
                ),
            ]
        )
    ]
