# Generated by Django 3.2.25 on 2024-07-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0036_auto_20240702_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='create_irods_user_account',
        ),
    ]
