# Generated by Django 3.2.25 on 2024-09-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0037_remove_userquota_and_userprofile_from_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_bucket_name',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
