# Generated by Django 4.2.20 on 2025-03-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0038_userprofile__bucket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='_bucket_name',
            field=models.CharField(editable=False, max_length=63, null=True, unique=True),
        ),
    ]
