# Generated by Django 4.2.20 on 2025-04-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0039_alter_userprofile__bucket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquota',
            name='allocated_value',
        ),
        migrations.RemoveField(
            model_name='userquota',
            name='unit',
        ),
    ]
