# Generated by Django 4.2.20 on 2025-05-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0040_remove_userquota_allocated_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotamessage',
            name='enforce_quota',
        ),
        migrations.RemoveField(
            model_name='quotamessage',
            name='grace_period',
        ),
        migrations.RemoveField(
            model_name='quotamessage',
            name='grace_period_content_prepend',
        ),
        migrations.RemoveField(
            model_name='quotamessage',
            name='hard_limit_percent',
        ),
        migrations.RemoveField(
            model_name='userquota',
            name='grace_period_ends',
        ),
    ]
