# Generated by Django 4.2.23 on 2026-03-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0041_remove_quotamessage_enforce_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquota',
            name='allocated_value',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='userquota',
            name='unit',
            field=models.CharField(default='GB', max_length=10),
        ),
    ]
