# Generated by Django 4.2.21 on 2025-06-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0041_remove_quotamessage_enforce_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='minio_access_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='minio_secret_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
