# Generated by Django 4.2.23 on 2026-06-17 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0042_userquota_allocated_value_userquota_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquota',
            name='allocated_value',
            field=models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='unit',
            field=models.CharField(choices=[('B', 'B'), ('MB', 'MB'), ('GB', 'GB'), ('TB', 'TB')], default='GB',
                                   max_length=10),
        ),
    ]
