# Generated by Django 4.2.23 on 2026-04-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0042_userquota_allocated_value_userquota_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquota',
            name='exceeded',
            field=models.BooleanField(default=False),
        ),
    ]
