# Generated by Django 4.2.23 on 2026-07-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0043_alter_userquota_allocated_value_alter_userquota_unit'),
        ('theme', '0043_userquota_exceeded'),
    ]

    operations = [
    ]
