# Generated by Django 4.2.30 on 2026-09-09 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0046_requestcommunity_cancelled'),
        ('theme', '0044_merge_20260723_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquota',
            name='required_community_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_user_quotas', to='hs_access_control.community'),
        ),
    ]