# Generated by Django 4.2.30 on 2026-09-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0042_userquota_required_community_membership'),
        ('theme', '0045_userquota_required_community_membership'),
    ]

    operations = [
    ]
