input:
  kafka_franz:
    seed_brokers:
      - "redpanda:9092"
    topics:
      - "resource_file"
    consumer_group: "hs_django"
pipeline:
  processors:
    - notify_hs_django_processor: {}
output:
  switch:
    cases:
      - check: errored()
        output:
          kafka_franz:
            seed_brokers:
              - "redpanda:9092"
            topic: "error_notifications"
      - output:
          drop: {}
