input:
  kafka_franz:
    seed_brokers:
      - "redpanda:9092" # Or your Redpanda broker addresses
    topics:
      - "resource_file"
    consumer_group: "hs_django"
pipeline:
  processors:
    - try:
        - notify_hs_django_processor: {}
        - bloblang: |
            root = if this == null { {} } else { this }
    - catch:
        - log:
            level: ERROR
            message: "notify_hs_django_processor failed: ${!error()}"
        - mapping: "root = deleted()"
output:
  stdout: {}